import * as Assert from 'node:assert/strict'
import * as Fs from 'node:fs'
import * as Os from 'node:os'
import * as Path from 'node:path'
import test from 'node:test'
import {
  AssertBuildTagMatchesRevision,
  AssertReleaseEventAllowed,
  BuildImageReleasePlan,
  ParseReleaseRef,
  ParseReleaseTag
} from '../sources/docker_image_release.js'
import {
  CollectRepositoryVersionPolicyViolations,
  RepositoryVersionPolicy
} from '../sources/repository_version_policy.js'
import { RunVersioning } from '../sources/versioning.js'

const PackageName = 'oxibelt'

/* oxlint-disable oxibelt/pascal-case -- Test fixtures mirror repository and release metadata keys. */
type Workspace = {
  root: string
  manifestPath: string
  lockfilePath: string
}

type ReleasePlanSummary = {
  tag: string
  kind: string
}
/* oxlint-enable oxibelt/pascal-case */

function WriteWorkspaceFile(Root: string, RelativePath: string, Content: string): void {
  const FilePath = Path.join(Root, RelativePath)
  Fs.mkdirSync(Path.dirname(FilePath), { recursive: true })
  Fs.writeFileSync(FilePath, Content)
}

function CreateWorkspace(ManifestVersion = '0.0.0', LockVersion = '0.0.0'): Workspace {
  const Root = Fs.mkdtempSync(Path.join(Os.tmpdir(), 'oxibelt-versioning-'))
  const ManifestPath = Path.join(Root, 'Cargo.toml')
  const LockfilePath = Path.join(Root, 'Cargo.lock')
  const RootCargoPackages = RepositoryVersionPolicy.cargoPackages.filter(
    Package => Package.lockfilePath === RepositoryVersionPolicy.lockfilePath
  )

  WriteWorkspaceFile(
    Root,
    RepositoryVersionPolicy.manifestPath,
    `[workspace]
members = [
${RootCargoPackages.map(Package => `  "${Path.posix.dirname(Package.manifestPath)}",`).join('\n')}
]

[workspace.package]
version = "${ManifestVersion}"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
publish = false
`
  )

  for (const Package of RepositoryVersionPolicy.cargoPackages) {
    const VersionField = Package.versionSource === 'workspace'
      ? 'version.workspace = true'
      : `version = "${ManifestVersion}"`
    WriteWorkspaceFile(
      Root,
      Package.manifestPath,
      `[package]
name = "${Package.name}"
${VersionField}
`
    )
  }

  const Lockfiles = new Map<
    string,
    Array<(typeof RepositoryVersionPolicy.cargoPackages)[number]>
  >()
  for (const Package of RepositoryVersionPolicy.cargoPackages) {
    const Packages = Lockfiles.get(Package.lockfilePath) ?? []
    Packages.push(Package)
    Lockfiles.set(Package.lockfilePath, Packages)
  }
  for (const [LockPath, Packages] of Lockfiles) {
    WriteWorkspaceFile(
      Root,
      LockPath,
      `# This file is automatically @generated by Cargo.
version = 4

${Packages.map(Package => `[[package]]
name = "${Package.name}"
version = "${LockVersion}"
`).join('\n')}

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "placeholder"
`
    )
  }

  WriteWorkspaceFile(
    Root,
    'package.json',
    `${JSON.stringify({
      name: 'oxibelt',
      private: true,
      workspaces: ['devops', 'ui/*']
    }, null, 2)}\n`
  )
  WriteWorkspaceFile(
    Root,
    RepositoryVersionPolicy.pnpmWorkspacePath,
    `packages:
${RepositoryVersionPolicy.npmWorkspacePatterns.map(Pattern => `  - "${Pattern}"`).join('\n')}
`
  )
  WriteWorkspaceFile(
    Root,
    'devops/package.json',
    `${JSON.stringify({
      name: '@oxibelt/devops',
      version: RepositoryVersionPolicy.committedVersion,
      private: true,
      type: 'module'
    }, null, 2)}\n`
  )
  WriteWorkspaceFile(
    Root,
    'ui/person-proof/package.json',
    `${JSON.stringify({
      name: '@oxibelt/person-proof-ui',
      version: RepositoryVersionPolicy.committedVersion,
      private: true,
      type: 'module'
    }, null, 2)}\n`
  )

  for (const ChartPath of RepositoryVersionPolicy.helmCharts) {
    WriteWorkspaceFile(
      Root,
      ChartPath,
      `apiVersion: v2
name: fixture
version: ${RepositoryVersionPolicy.committedVersion}
appVersion: "${RepositoryVersionPolicy.committedVersion}"
`
    )
  }

  WriteWorkspaceFile(
    Root,
    RepositoryVersionPolicy.dockerfilePath,
    `ARG OXIBELT_BUILD_VERSION=${RepositoryVersionPolicy.archiveIdentity.version}
ARG OXIBELT_BUILD_REVISION=${RepositoryVersionPolicy.archiveIdentity.revision}
ARG OXIBELT_BUILD_REF=${RepositoryVersionPolicy.archiveIdentity.ref}
ARG OXIBELT_BUILD_DIRTY=${RepositoryVersionPolicy.archiveIdentity.dirty}
ARG OXIBELT_BUILD_KIND=${RepositoryVersionPolicy.archiveIdentity.kind}
ARG OXIBELT_REF_NAME=${RepositoryVersionPolicy.archiveIdentity.version}

FROM scratch
`
  )
  WriteWorkspaceFile(
    Root,
    RepositoryVersionPolicy.releaseHelperPath,
    `derived_revision=""
derived_dirty="${RepositoryVersionPolicy.archiveIdentity.dirty}"
derived_kind="${RepositoryVersionPolicy.archiveIdentity.kind}"
derived_ref="${RepositoryVersionPolicy.archiveIdentity.ref}"
derived_version="${RepositoryVersionPolicy.archiveIdentity.version}"
if [[ "\${derived_revision}" =~ ^[0-9a-f]{40}$ ]]; then
  derived_dirty="clean"
  derived_dirty="dirty"
  derived_ref="$(git -C "\${repo_root}" symbolic-ref -q HEAD 2>/dev/null || true)"
  derived_kind="tagged_development"
  derived_ref="refs/tags/\${release_tag}"
  derived_version="\${release_tag}"
  derived_kind="git_development"
  derived_version="0.0.0-dev.g\${derived_revision:0:8}"
  derived_version="\${derived_version}+dirty"
fi
oxibelt_version="\${OXIBELT_DOCKER_IMAGE_VERSION:-\${derived_version}}"
oxibelt_revision="\${OXIBELT_DOCKER_IMAGE_REVISION:-\${derived_revision:-unknown}}"
oxibelt_source_ref="\${OXIBELT_DOCKER_IMAGE_SOURCE_REF:-\${derived_ref}}"
oxibelt_source_dirty="\${OXIBELT_DOCKER_IMAGE_SOURCE_DIRTY:-\${derived_dirty}}"
oxibelt_build_kind="\${OXIBELT_DOCKER_IMAGE_BUILD_KIND:-\${derived_kind}}"
oxibelt_ref_name="\${OXIBELT_DOCKER_IMAGE_REF_NAME:-\${oxibelt_version}}"
case "\${artifact_arch}" in
esac
if [[ -z "\${oxibelt_revision}" ]]; then
  oxibelt_revision="unknown"
fi
`
  )
  WriteWorkspaceFile(
    Root,
    RepositoryVersionPolicy.archiveIdentitySourcePath,
    `${Array.from(
      { length: RepositoryVersionPolicy.archiveVersionLiteralOccurrences },
      () => JSON.stringify(RepositoryVersionPolicy.archiveIdentity.version)
    ).join('\n')}\n`
  )

  return { root: Root, manifestPath: ManifestPath, lockfilePath: LockfilePath }
}

function Cleanup(WorkspaceValue: Workspace): void {
  Fs.rmSync(WorkspaceValue.root, { force: true, recursive: true })
}

function ReplaceWorkspaceText(
  WorkspaceValue: Workspace,
  RelativePath: string,
  Search: string,
  Replacement: string
): void {
  const FilePath = Path.join(WorkspaceValue.root, RelativePath)
  const Content = Fs.readFileSync(FilePath, 'utf8')
  const Next = Content.replace(Search, Replacement)
  if (Next === Content) {
    throw new Error(`fixture replacement did not match ${RelativePath}: ${Search}`)
  }
  Fs.writeFileSync(FilePath, Next)
}

function PolicyFilePaths(): string[] {
  return [...new Set([
    RepositoryVersionPolicy.manifestPath,
    RepositoryVersionPolicy.lockfilePath,
    ...RepositoryVersionPolicy.cargoPackages.flatMap(Package => [
      Package.manifestPath,
      Package.lockfilePath
    ]),
    ...RepositoryVersionPolicy.npmPackages.map(Package => Package.packagePath),
    RepositoryVersionPolicy.pnpmWorkspacePath,
    ...RepositoryVersionPolicy.helmCharts,
    RepositoryVersionPolicy.dockerfilePath,
    RepositoryVersionPolicy.releaseHelperPath,
    RepositoryVersionPolicy.archiveIdentitySourcePath
  ])].sort()
}

function SnapshotPolicyFiles(WorkspaceValue: Workspace): Map<string, string> {
  return new Map(PolicyFilePaths().map(RelativePath => [
    RelativePath,
    Fs.readFileSync(Path.join(WorkspaceValue.root, RelativePath), 'utf8')
  ]))
}

function LockPackageVersion(Content: string, PackageNameValue: string): string {
  const EscapedName = PackageNameValue.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const Match = new RegExp(
    `\\[\\[package\\]\\]\\s+name = "${EscapedName}"\\s+version = "([^"]+)"`,
    'm'
  ).exec(Content)
  if (Match === null) {
    throw new Error(`lock fixture is missing ${PackageNameValue}`)
  }
  return Match[1]
}

function AssertRepresentativeManifestArchs(
  Plan: ReturnType<typeof BuildImageReleasePlan>,
  Role: 'standalone' | 'dataplane' | 'dataplane-strict' | 'controller' | 'tools' | 'keysigner' = 'standalone'
): void {
  const ExpectedArchs = ['amd64', 'arm64', 'riscv64']
  const ReleaseManifest = Plan.manifests.find(Manifest => Manifest.role === Role && Manifest.name === 'release')
  const AlpineMuslManifest = Plan.manifests.find(
    Manifest => Manifest.role === Role && Manifest.name === 'alpine-musl'
  )
  const Amd64 = Plan.artifacts.find(Artifact => Artifact.role === Role && Artifact.artifactArch === 'amd64')

  if (ReleaseManifest === undefined || AlpineMuslManifest === undefined) {
    throw new Error('image plan should include representative release and alpine-musl manifests')
  }
  if (Amd64 === undefined) {
    throw new Error('image plan should include the amd64 artifact')
  }

  Assert.deepEqual(ReleaseManifest.artifactArchs, ExpectedArchs)
  Assert.deepEqual(AlpineMuslManifest.artifactArchs, ExpectedArchs)
  Assert.equal(ReleaseManifest.artifactArchs.includes('amd64v2'), false)
  Assert.equal(AlpineMuslManifest.artifactArchs.includes('amd64v2'), false)
  Assert.equal(Amd64.platform, 'linux/amd64')
  Assert.equal(Amd64.dockerArchitecture, 'amd64')
  Assert.equal(Amd64.targetCpu, 'x86-64-v3')
}

test('strict release tag parser accepts stable, beta, and build tags', () => {
  Assert.deepEqual(ParseReleaseTag('15.2.0'), {
    tag: '15.2.0',
    major: '15',
    minor: '2',
    patch: '0',
    kind: 'stable'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-beta.4'), {
    tag: '1.5.0-beta.4',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'beta',
    betaNumber: '4'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-build.4f43abcd'), {
    tag: '1.5.0-build.4f43abcd',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'build',
    buildCommitPrefix: '4f43abcd'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-build.44372848'), {
    tag: '1.5.0-build.44372848',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'build',
    buildCommitPrefix: '44372848'
  })
})

test('strict release tag parser rejects v prefixes and unsupported semver shapes', () => {
  for (const Tag of [
    'v1.2.3',
    '01.2.3',
    '1.02.3',
    '1.2.03',
    '1.2.3+build.4',
    '1.2.3-alpha.1',
    '1.2.3-beta.01',
    '1.2.3-build.01234567',
    '1.2.3-build.4f43abc',
    '1.2.3-build.4f43abcg',
    '1.2'
  ]) {
    Assert.throws(() => ParseReleaseTag(Tag), /release tag/)
  }
})

test('release refs must be tag refs without v prefixes', () => {
  Assert.equal(ParseReleaseRef('refs/tags/1.2.3').tag, '1.2.3')
  Assert.throws(() => ParseReleaseRef('refs/heads/main'), /refs\/tags/)
  Assert.throws(() => ParseReleaseRef('refs/tags/v1.2.3'), /leading v/)
})

test('build release tags must match the release commit prefix', () => {
  const Tag = ParseReleaseTag('1.5.0-build.4f43abcd')

  AssertBuildTagMatchesRevision(Tag, '4f43abcd99999999999999999999999999999999')
  Assert.throws(
    () => AssertBuildTagMatchesRevision(Tag, 'ffffffff99999999999999999999999999999999'),
    /must end with the first 8/
  )
})

test('event policy allows push only for build tags', () => {
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-build.4f43abcd'), 'push', undefined)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'release', false)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-beta.1'), 'release', true)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'workflow_dispatch', undefined)
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'push', undefined),
    /must publish from release or workflow_dispatch/
  )
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-beta.1'), 'release', false),
    /must be published from a GitHub prerelease/
  )
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'release', true),
    /must not be published from a GitHub prerelease/
  )
})

test('check mode accepts the complete development policy without writing files', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  const Before = SnapshotPolicyFiles(WorkspaceValue)
  TestContext.after(() => Cleanup(WorkspaceValue))

  const Result = RunVersioning({
    workspacePath: WorkspaceValue.root,
    manifestPath: 'Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    releasePublish: false
  })

  Assert.deepEqual(Result, {
    mode: 'check',
    packageName: PackageName,
    version: '0.0.0'
  })
  Assert.deepEqual(SnapshotPolicyFiles(WorkspaceValue), Before)
})

test('check mode rejects mismatched committed Cargo versions', TestContext => {
  const WorkspaceValue = CreateWorkspace('0.0.0', '0.2.0')
  TestContext.after(() => Cleanup(WorkspaceValue))

  Assert.throws(
    () => RunVersioning({
      workspacePath: WorkspaceValue.root,
      manifestPath: 'Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    /Cargo[.]lock \[\[package\]\] oxibelt[.]version: expected "0[.]0[.]0", found "0[.]2[.]0"/
  )
})

test('check mode rejects synchronized committed release versions', TestContext => {
  const WorkspaceValue = CreateWorkspace('0.7.0', '0.7.0')
  const Before = SnapshotPolicyFiles(WorkspaceValue)
  TestContext.after(() => Cleanup(WorkspaceValue))

  Assert.throws(
    () => RunVersioning({
      workspacePath: WorkspaceValue.root,
      manifestPath: 'Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    /committed repository version policy/
  )
  Assert.deepEqual(SnapshotPolicyFiles(WorkspaceValue), Before)
})

test('policy collector reports every Cargo, npm, Helm, Docker, and helper drift', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  TestContext.after(() => Cleanup(WorkspaceValue))

  ReplaceWorkspaceText(
    WorkspaceValue,
    'Cargo.toml',
    'version = "0.0.0"',
    'version = "0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    'source/Cargo.toml',
    'version.workspace = true',
    'version = "0.0.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    'Cargo.lock',
    'name = "oxibelt"\nversion = "0.0.0"',
    'name = "oxibelt"\nversion = "0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    'tests/docker/perf_probe/Cargo.toml',
    'version = "0.0.0"',
    'version = "0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    'tests/docker/perf_probe/Cargo.lock',
    'version = "0.0.0"',
    'version = "0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    'devops/package.json',
    '"version": "0.0.0"',
    '"version": "0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    RepositoryVersionPolicy.pnpmWorkspacePath,
    '  - "devops"',
    '  - "ui/*"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    'deploy/helm/oxibelt/Chart.yaml',
    'appVersion: "0.0.0"',
    'appVersion: "0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    RepositoryVersionPolicy.dockerfilePath,
    'ARG OXIBELT_BUILD_VERSION=0.0.0-dev.archive',
    'ARG OXIBELT_BUILD_VERSION=0.7.0'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    RepositoryVersionPolicy.releaseHelperPath,
    'derived_version="0.0.0-dev.archive"',
    'derived_version="0.7.0"'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    RepositoryVersionPolicy.archiveIdentitySourcePath,
    '"0.0.0-dev.archive"',
    '"0.7.0"'
  )

  const Report = CollectRepositoryVersionPolicyViolations(WorkspaceValue.root)
  const Paths = new Set(Report.violations.map(Violation => Violation.path))
  for (const ExpectedPath of [
    'Cargo.toml',
    'source/Cargo.toml',
    'Cargo.lock',
    'tests/docker/perf_probe/Cargo.toml',
    'tests/docker/perf_probe/Cargo.lock',
    'devops/package.json',
    RepositoryVersionPolicy.pnpmWorkspacePath,
    'deploy/helm/oxibelt/Chart.yaml',
    RepositoryVersionPolicy.dockerfilePath,
    RepositoryVersionPolicy.releaseHelperPath,
    RepositoryVersionPolicy.archiveIdentitySourcePath
  ]) {
    Assert.equal(Paths.has(ExpectedPath), true, `policy report should include ${ExpectedPath}`)
  }

  Assert.throws(
    () => RunVersioning({
      workspacePath: WorkspaceValue.root,
      manifestPath: 'Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    ErrorValue => {
      Assert.ok(ErrorValue instanceof Error)
      for (const ExpectedPath of Paths) {
        Assert.match(ErrorValue.message, new RegExp(ExpectedPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
      }
      return true
    }
  )
})

test('policy collector reports missing, malformed, and duplicate fields', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  TestContext.after(() => Cleanup(WorkspaceValue))

  Fs.rmSync(Path.join(WorkspaceValue.root, 'ui/person-proof/package.json'))
  Fs.writeFileSync(Path.join(WorkspaceValue.root, 'devops/package.json'), '{')
  ReplaceWorkspaceText(
    WorkspaceValue,
    RepositoryVersionPolicy.dockerfilePath,
    'ARG OXIBELT_REF_NAME=0.0.0-dev.archive\n\nFROM scratch',
    'ARG OXIBELT_REF_NAME=0.0.0-dev.archive\n' +
      '  arg OXIBELT_REF_NAME=0.7.0\n\n' +
      'FROM scratch\n  arg OXIBELT_BUILD_VERSION=0.7.0'
  )
  ReplaceWorkspaceText(
    WorkspaceValue,
    RepositoryVersionPolicy.releaseHelperPath,
    'derived_version="0.0.0-dev.archive"',
    'derived_version="0.0.0-dev.archive"\n  derived_version="0.7.0"'
  )

  const Report = CollectRepositoryVersionPolicyViolations(WorkspaceValue.root)
  Assert.ok(Report.violations.some(Violation =>
    Violation.path === 'ui/person-proof/package.json' && Violation.field === '<file>'
  ))
  Assert.ok(Report.violations.some(Violation =>
    Violation.path === 'devops/package.json' && Violation.field === '<json>'
  ))
  Assert.ok(Report.violations.some(Violation =>
    Violation.path === RepositoryVersionPolicy.dockerfilePath &&
      Violation.field === 'OXIBELT_REF_NAME' &&
      Violation.actual === '<duplicate:2>'
  ))
  Assert.ok(Report.violations.some(Violation =>
    Violation.path === RepositoryVersionPolicy.dockerfilePath &&
      Violation.field === 'OXIBELT_BUILD_VERSION stage defaults' &&
      Violation.actual === '0.7.0'
  ))
  Assert.ok(Report.violations.some(Violation =>
    Violation.path === RepositoryVersionPolicy.releaseHelperPath &&
      Violation.field === 'derived_version assignments'
  ))
})

test('release mode rewrites Cargo versions and emits the image plan', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  const ImagePlanOutput = Path.join(WorkspaceValue.root, 'image-plan.json')
  const Before = SnapshotPolicyFiles(WorkspaceValue)
  TestContext.after(() => Cleanup(WorkspaceValue))

  const Result = RunVersioning({
    workspacePath: WorkspaceValue.root,
    manifestPath: 'Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    ref: 'refs/tags/1.5.0-beta.1',
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    eventName: 'release',
    releasePrerelease: true,
    releasePublish: true,
    imagePlanOutput: ImagePlanOutput
  })

  const Manifest = Fs.readFileSync(WorkspaceValue.manifestPath, 'utf8')
  const Plan = JSON.parse(Fs.readFileSync(ImagePlanOutput, 'utf8')) as ReleasePlanSummary

  Assert.deepEqual(Result, {
    mode: 'release',
    packageName: PackageName,
    version: '1.5.0-beta.1'
  })
  Assert.match(Manifest, /^version = "1\.5\.0-beta\.1"$/m)
  Assert.match(Manifest, /^publish = false$/m)
  for (const Package of RepositoryVersionPolicy.cargoPackages) {
    const Expected = Package.releaseRewrite ? '1.5.0-beta.1' : RepositoryVersionPolicy.committedVersion
    Assert.equal(LockPackageVersion(
      Fs.readFileSync(Path.join(WorkspaceValue.root, Package.lockfilePath), 'utf8'),
      Package.name
    ), Expected)
  }
  for (const [RelativePath, Content] of Before) {
    if (
      RelativePath !== RepositoryVersionPolicy.manifestPath &&
      RelativePath !== RepositoryVersionPolicy.lockfilePath
    ) {
      Assert.equal(
        Fs.readFileSync(Path.join(WorkspaceValue.root, RelativePath), 'utf8'),
        Content,
        `release mode should not rewrite ${RelativePath}`
      )
    }
  }
  Assert.equal(Plan.tag, '1.5.0-beta.1')
  Assert.equal(Plan.kind, 'beta')
})

test('invalid release input does not rewrite policy files or emit a plan', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  const ImagePlanOutput = Path.join(WorkspaceValue.root, 'image-plan.json')
  const Before = SnapshotPolicyFiles(WorkspaceValue)
  TestContext.after(() => Cleanup(WorkspaceValue))

  Assert.throws(
    () => RunVersioning({
      workspacePath: WorkspaceValue.root,
      manifestPath: 'Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      ref: 'refs/tags/1.5.0-build.4f43abcd',
      revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      eventName: 'push',
      releasePublish: true,
      imagePlanOutput: ImagePlanOutput
    }),
    /must end with the first 8/
  )

  Assert.deepEqual(SnapshotPolicyFiles(WorkspaceValue), Before)
  Assert.equal(Fs.existsSync(ImagePlanOutput), false)
})

test('release output preflight prevents empty, colliding, or unavailable writes', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  const Before = SnapshotPolicyFiles(WorkspaceValue)
  TestContext.after(() => Cleanup(WorkspaceValue))

  for (const [ImagePlanOutput, Expected] of [
    ['', /image plan output must not be empty/],
    ['Cargo.toml', /must not overwrite Cargo[.]toml or Cargo[.]lock/],
    [Path.join(WorkspaceValue.root, 'missing', 'image-plan.json'), /directory does not exist/]
  ] as const) {
    Assert.throws(
      () => RunVersioning({
        workspacePath: WorkspaceValue.root,
        manifestPath: 'Cargo.toml',
        lockfilePath: 'Cargo.lock',
        packageName: PackageName,
        ref: 'refs/tags/1.5.0',
        revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        eventName: 'release',
        releasePrerelease: false,
        releasePublish: true,
        imagePlanOutput: ImagePlanOutput
      }),
      Expected
    )
    Assert.deepEqual(SnapshotPolicyFiles(WorkspaceValue), Before)
  }
})

test('stable image plan includes major aliases and stable manifest tags', () => {
  const Plan = BuildImageReleasePlan({
    releaseTag: ParseReleaseTag('5.2.0'),
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    source: 'https://github.com/OxiBelt/OxiBelt'
  })
  const Amd64 = Plan.artifacts.find(
    Artifact => Artifact.role === 'standalone' && Artifact.artifactArch === 'amd64'
  )

  if (Amd64 === undefined) {
    throw new Error('stable image plan should include the amd64 artifact')
  }
  AssertRepresentativeManifestArchs(Plan)
  Assert.equal(Amd64.canonicalGhcrTag, 'ghcr.io/oxibelt/oxibelt:5.2.0-alpine-musl-amd64')
  Assert.deepEqual(Amd64.aliasGhcrTags, ['ghcr.io/oxibelt/oxibelt:5-alpine-musl-amd64'])
  Assert.deepEqual(Plan.manifests[0].aliasGhcrTags, ['ghcr.io/oxibelt/oxibelt:latest'])
  Assert.deepEqual(Plan.manifests[1].aliasGhcrTags, [
    'ghcr.io/oxibelt/oxibelt:5-alpine-musl',
    'ghcr.io/oxibelt/oxibelt:alpine-musl'
  ])
  const ActualAliases = [
    ...Plan.artifacts.flatMap(Artifact => Artifact.aliasGhcrTags.map(Alias => ({
      alias: Alias,
      sourceTag: Artifact.canonicalGhcrTag,
      kind: 'platform'
    }))),
    ...Plan.manifests.flatMap(Manifest => Manifest.aliasGhcrTags.map(Alias => ({
      alias: Alias,
      sourceTag: Manifest.canonicalGhcrTag,
      kind: 'index'
    })))
  ].sort((Left, Right) => Left.alias.localeCompare(Right.alias))
  const ArtifactArchs = ['amd64v2', 'amd64', 'amd64v4', 'arm64', 'riscv64'] as const
  const ExpectedAliases = Plan.roles.flatMap(Role => [
    ...ArtifactArchs.map(ArtifactArch => ({
      alias: `${Role.image}:5-alpine-musl-${ArtifactArch}`,
      sourceTag: `${Role.image}:5.2.0-alpine-musl-${ArtifactArch}`,
      kind: 'platform'
    })),
    {
      alias: `${Role.image}:latest`,
      sourceTag: `${Role.image}:5.2.0`,
      kind: 'index'
    },
    {
      alias: `${Role.image}:5-alpine-musl`,
      sourceTag: `${Role.image}:5.2.0-alpine-musl`,
      kind: 'index'
    },
    {
      alias: `${Role.image}:alpine-musl`,
      sourceTag: `${Role.image}:5.2.0-alpine-musl`,
      kind: 'index'
    }
  ]).sort((Left, Right) => Left.alias.localeCompare(Right.alias))
  Assert.equal(ActualAliases.length, 48)
  Assert.equal(new Set(ActualAliases.map(Alias => Alias.alias)).size, 48)
  Assert.deepEqual(ActualAliases, ExpectedAliases)
  Assert.equal(Plan.schemaVersion, 8)
  Assert.equal(Plan.sourceRef, 'refs/tags/5.2.0')
  Assert.equal(Plan.sourceDirty, 'clean')
  Assert.equal(Plan.buildKind, 'official_release')
  Assert.deepEqual(Plan.roles, [
    {
      role: 'standalone',
      image: 'ghcr.io/oxibelt/oxibelt',
      dockerTarget: 'standalone',
      binaries: ['oxibelt', 'oxibeltctl', 'oxibelt-keysigner', 'oxibelt-netport-switcher'],
      entrypoint: ['/usr/local/bin/oxibelt', '--config', '/etc/oxibelt/config/oxibelt.toml'],
      user: '10001:10001',
      ports: ['8443/tcp', '8443/udp'],
      embeddedAssets: ['admin-openapi', 'person-proof']
    },
    {
      role: 'dataplane',
      image: 'ghcr.io/oxibelt/oxibelt-dataplane',
      dockerTarget: 'dataplane',
      binaries: ['oxibelt'],
      entrypoint: ['/usr/local/bin/oxibelt', '--config', '/etc/oxibelt/config/oxibelt.toml'],
      user: '10001:10001',
      ports: ['8443/tcp', '8443/udp'],
      embeddedAssets: ['admin-openapi', 'person-proof']
    },
    {
      role: 'dataplane-strict',
      image: 'ghcr.io/oxibelt/oxibelt-dataplane-strict',
      dockerTarget: 'dataplane-strict',
      binaries: ['oxibelt-dataplane-strict'],
      entrypoint: ['/usr/local/bin/oxibelt-dataplane-strict', '--config', '/etc/oxibelt/config/oxibelt.toml'],
      user: '10001:10001',
      ports: ['8443/tcp', '8443/udp'],
      embeddedAssets: ['person-proof']
    },
    {
      role: 'controller',
      image: 'ghcr.io/oxibelt/oxibelt-gateway-controller',
      dockerTarget: 'controller',
      binaries: ['oxibelt-gateway-controller'],
      entrypoint: ['/usr/local/bin/oxibelt-gateway-controller'],
      user: '10001:10001',
      ports: [],
      embeddedAssets: []
    },
    {
      role: 'tools',
      image: 'ghcr.io/oxibelt/oxibelt-tools',
      dockerTarget: 'tools',
      binaries: ['oxibeltctl'],
      entrypoint: ['/usr/local/bin/oxibeltctl'],
      user: '10001:10001',
      ports: [],
      embeddedAssets: []
    },
    {
      role: 'keysigner',
      image: 'ghcr.io/oxibelt/oxibelt-keysigner',
      dockerTarget: 'keysigner',
      binaries: ['oxibelt-keysigner'],
      entrypoint: ['/usr/local/bin/oxibelt-keysigner'],
      user: '10002:10002',
      ports: [],
      embeddedAssets: []
    }
  ])
  Assert.equal('sbom' in Plan, false)
  Assert.equal('supplyChain' in Plan, false)
  Assert.equal('sbomArtifactName' in Amd64, false)
  Assert.equal('sbomFile' in Amd64, false)
})

test('image plan defines exact role-specific repositories, inventories, and artifacts', () => {
  const Plan = BuildImageReleasePlan({
    releaseTag: ParseReleaseTag('5.2.0'),
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    source: 'https://github.com/OxiBelt/OxiBelt'
  })

  Assert.equal(Plan.artifacts.length, 30)
  Assert.equal(Plan.manifests.length, 12)
  for (const Role of ['standalone', 'dataplane', 'dataplane-strict', 'controller', 'tools', 'keysigner'] as const) {
    AssertRepresentativeManifestArchs(Plan, Role)
    Assert.equal(Plan.artifacts.filter(Artifact => Artifact.role === Role).length, 5)
    Assert.equal(Plan.manifests.filter(Manifest => Manifest.role === Role).length, 2)
  }

  const Dataplane = Plan.artifacts.find(
    Artifact => Artifact.role === 'dataplane' && Artifact.artifactArch === 'amd64'
  )
  Assert.equal(Dataplane?.dockerTarget, 'dataplane')
  Assert.deepEqual(Dataplane?.binaries, ['oxibelt'])
  Assert.equal(
    Dataplane?.canonicalGhcrTag,
    'ghcr.io/oxibelt/oxibelt-dataplane:5.2.0-alpine-musl-amd64'
  )
  Assert.equal(Dataplane?.artifactName, 'oxibelt-dataplane-alpine-musl-amd64-image')

  const Strict = Plan.artifacts.find(
    Artifact => Artifact.role === 'dataplane-strict' && Artifact.artifactArch === 'amd64'
  )
  Assert.equal(Strict?.dockerTarget, 'dataplane-strict')
  Assert.deepEqual(Strict?.binaries, ['oxibelt-dataplane-strict'])
  Assert.deepEqual(Strict?.embeddedAssets, ['person-proof'])
  Assert.equal(
    Strict?.canonicalGhcrTag,
    'ghcr.io/oxibelt/oxibelt-dataplane-strict:5.2.0-alpine-musl-amd64'
  )
})

test('beta and build image plans use amd64 representative manifests', () => {
  for (const Tag of ['5.2.0-beta.1', '5.2.0-build.4f43abcd']) {
    const Plan = BuildImageReleasePlan({
      releaseTag: ParseReleaseTag(Tag),
      revision: '4f43abcd99999999999999999999999999999999',
      source: 'https://github.com/OxiBelt/OxiBelt'
    })

    AssertRepresentativeManifestArchs(Plan)
  }
})

test('beta and build image plans do not include latest or major aliases', () => {
  for (const Tag of ['5.2.0-beta.1', '5.2.0-build.4f43abcd']) {
    const Plan = BuildImageReleasePlan({
      releaseTag: ParseReleaseTag(Tag),
      revision: '4f43abcd99999999999999999999999999999999',
      source: 'https://github.com/OxiBelt/OxiBelt'
    })
    const Serialized = JSON.stringify(Plan)

    Assert.equal(Serialized.includes(':latest'), false)
    Assert.equal(Serialized.includes(':5-alpine-musl'), false)
    Assert.deepEqual(Plan.artifacts.flatMap(Artifact => Artifact.aliasGhcrTags), [])
    Assert.deepEqual(Plan.manifests.flatMap(Manifest => Manifest.aliasGhcrTags), [])
  }
})
