import * as Assert from 'node:assert/strict'
import * as Fs from 'node:fs'
import * as Os from 'node:os'
import * as Path from 'node:path'
import test from 'node:test'
import {
  AssertBuildTagMatchesRevision,
  AssertReleaseEventAllowed,
  BuildImageReleasePlan,
  ParseReleaseRef,
  ParseReleaseTag
} from '../sources/docker_image_release.js'
import { RunVersioning } from '../sources/versioning.js'

const PackageName = 'oxibelt'

/* eslint-disable @typescript-eslint/naming-convention -- Test fixtures mirror repository and release metadata keys. */
type Workspace = {
  root: string
  manifestPath: string
  lockfilePath: string
}

type ReleasePlanSummary = {
  tag: string
  kind: string
}
/* eslint-enable @typescript-eslint/naming-convention */

function CreateWorkspace(ManifestVersion = '0.0.0', LockVersion = '0.0.0'): Workspace {
  const Root = Fs.mkdtempSync(Path.join(Os.tmpdir(), 'oxibelt-versioning-'))
  const ManifestPath = Path.join(Root, 'Cargo.toml')
  const LockfilePath = Path.join(Root, 'Cargo.lock')

  Fs.writeFileSync(
    ManifestPath,
    `[workspace]
members = []

[workspace.package]
version = "${ManifestVersion}"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
publish = false
`
  )

  const ProductionPackages = [
    'oxibelt',
    'oxibelt-build-identity',
    'oxibelt-dataplane-strict',
    'oxibelt-control-http',
    'oxibelt-control-protocol',
    'oxibelt-deployment-diagnostics',
    'oxibelt-gateway-controller',
    'oxibelt-keysigner',
    'oxibelt-netport-switcher',
    'oxibeltctl'
  ]
  Fs.writeFileSync(
    LockfilePath,
    `# This file is automatically @generated by Cargo.
version = 4

${ProductionPackages.map(Name => `[[package]]
name = "${Name}"
version = "${LockVersion}"
`).join('\n')}

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "placeholder"
`
  )

  return { root: Root, manifestPath: ManifestPath, lockfilePath: LockfilePath }
}

function Cleanup(WorkspaceValue: Workspace): void {
  Fs.rmSync(WorkspaceValue.root, { force: true, recursive: true })
}

function AssertRepresentativeManifestArchs(
  Plan: ReturnType<typeof BuildImageReleasePlan>,
  Role: 'standalone' | 'dataplane' | 'dataplane-strict' | 'controller' | 'tools' | 'keysigner' = 'standalone'
): void {
  const ExpectedArchs = ['amd64', 'arm64', 'riscv64']
  const ReleaseManifest = Plan.manifests.find(Manifest => Manifest.role === Role && Manifest.name === 'release')
  const AlpineMuslManifest = Plan.manifests.find(
    Manifest => Manifest.role === Role && Manifest.name === 'alpine-musl'
  )
  const Amd64 = Plan.artifacts.find(Artifact => Artifact.role === Role && Artifact.artifactArch === 'amd64')

  if (ReleaseManifest === undefined || AlpineMuslManifest === undefined) {
    throw new Error('image plan should include representative release and alpine-musl manifests')
  }
  if (Amd64 === undefined) {
    throw new Error('image plan should include the amd64 artifact')
  }

  Assert.deepEqual(ReleaseManifest.artifactArchs, ExpectedArchs)
  Assert.deepEqual(AlpineMuslManifest.artifactArchs, ExpectedArchs)
  Assert.equal(ReleaseManifest.artifactArchs.includes('amd64v2'), false)
  Assert.equal(AlpineMuslManifest.artifactArchs.includes('amd64v2'), false)
  Assert.equal(Amd64.platform, 'linux/amd64')
  Assert.equal(Amd64.dockerArchitecture, 'amd64')
  Assert.equal(Amd64.targetCpu, 'x86-64-v3')
}

test('strict release tag parser accepts stable, beta, and build tags', () => {
  Assert.deepEqual(ParseReleaseTag('15.2.0'), {
    tag: '15.2.0',
    major: '15',
    minor: '2',
    patch: '0',
    kind: 'stable'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-beta.4'), {
    tag: '1.5.0-beta.4',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'beta',
    betaNumber: '4'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-build.4f43abcd'), {
    tag: '1.5.0-build.4f43abcd',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'build',
    buildCommitPrefix: '4f43abcd'
  })
})

test('strict release tag parser rejects v prefixes and unsupported semver shapes', () => {
  for (const Tag of [
    'v1.2.3',
    '01.2.3',
    '1.02.3',
    '1.2.03',
    '1.2.3+build.4',
    '1.2.3-alpha.1',
    '1.2.3-beta.01',
    '1.2.3-build.4f43abc',
    '1.2.3-build.4f43abcg',
    '1.2'
  ]) {
    Assert.throws(() => ParseReleaseTag(Tag), /release tag/)
  }
})

test('release refs must be tag refs without v prefixes', () => {
  Assert.equal(ParseReleaseRef('refs/tags/1.2.3').tag, '1.2.3')
  Assert.throws(() => ParseReleaseRef('refs/heads/main'), /refs\/tags/)
  Assert.throws(() => ParseReleaseRef('refs/tags/v1.2.3'), /leading v/)
})

test('build release tags must match the release commit prefix', () => {
  const Tag = ParseReleaseTag('1.5.0-build.4f43abcd')

  AssertBuildTagMatchesRevision(Tag, '4f43abcd99999999999999999999999999999999')
  Assert.throws(
    () => AssertBuildTagMatchesRevision(Tag, 'ffffffff99999999999999999999999999999999'),
    /must end with the first 8/
  )
})

test('event policy allows push only for build tags', () => {
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-build.4f43abcd'), 'push', undefined)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'release', false)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-beta.1'), 'release', true)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'workflow_dispatch', undefined)
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'push', undefined),
    /must publish from release or workflow_dispatch/
  )
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-beta.1'), 'release', false),
    /must be published from a GitHub prerelease/
  )
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'release', true),
    /must not be published from a GitHub prerelease/
  )
})

test('check mode accepts matching committed Cargo versions', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  TestContext.after(() => Cleanup(WorkspaceValue))

  const Result = RunVersioning({
    workspacePath: WorkspaceValue.root,
    manifestPath: 'Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    releasePublish: false
  })

  Assert.deepEqual(Result, {
    mode: 'check',
    packageName: PackageName,
    version: '0.0.0'
  })
})

test('check mode rejects mismatched committed Cargo versions', TestContext => {
  const WorkspaceValue = CreateWorkspace('0.0.0', '0.2.0')
  TestContext.after(() => Cleanup(WorkspaceValue))

  Assert.throws(
    () => RunVersioning({
      workspacePath: WorkspaceValue.root,
      manifestPath: 'Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    /version must match/
  )
})

test('release mode rewrites Cargo versions and emits the image plan', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  const ImagePlanOutput = Path.join(WorkspaceValue.root, 'image-plan.json')
  TestContext.after(() => Cleanup(WorkspaceValue))

  const Result = RunVersioning({
    workspacePath: WorkspaceValue.root,
    manifestPath: 'Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    ref: 'refs/tags/1.5.0-beta.1',
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    eventName: 'release',
    releasePrerelease: true,
    releasePublish: true,
    imagePlanOutput: ImagePlanOutput
  })

  const Manifest = Fs.readFileSync(WorkspaceValue.manifestPath, 'utf8')
  const Lockfile = Fs.readFileSync(WorkspaceValue.lockfilePath, 'utf8')
  const Plan = JSON.parse(Fs.readFileSync(ImagePlanOutput, 'utf8')) as ReleasePlanSummary

  Assert.deepEqual(Result, {
    mode: 'release',
    packageName: PackageName,
    version: '1.5.0-beta.1'
  })
  Assert.match(Manifest, /^version = "1\.5\.0-beta\.1"$/m)
  Assert.match(Manifest, /^publish = false$/m)
  Assert.match(Lockfile, /^version = "1\.5\.0-beta\.1"$/m)
  Assert.equal(Plan.tag, '1.5.0-beta.1')
  Assert.equal(Plan.kind, 'beta')
})

test('stable image plan includes major aliases and stable manifest tags', () => {
  const Plan = BuildImageReleasePlan({
    releaseTag: ParseReleaseTag('5.2.0'),
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    source: 'https://github.com/OxiBelt/OxiBelt'
  })
  const Amd64 = Plan.artifacts.find(
    Artifact => Artifact.role === 'standalone' && Artifact.artifactArch === 'amd64'
  )

  if (Amd64 === undefined) {
    throw new Error('stable image plan should include the amd64 artifact')
  }
  AssertRepresentativeManifestArchs(Plan)
  Assert.equal(Amd64.canonicalGhcrTag, 'ghcr.io/oxibelt/oxibelt:5.2.0-alpine-musl-amd64')
  Assert.deepEqual(Amd64.aliasGhcrTags, ['ghcr.io/oxibelt/oxibelt:5-alpine-musl-amd64'])
  Assert.deepEqual(Plan.manifests[0].aliasGhcrTags, ['ghcr.io/oxibelt/oxibelt:latest'])
  Assert.deepEqual(Plan.manifests[1].aliasGhcrTags, [
    'ghcr.io/oxibelt/oxibelt:5-alpine-musl',
    'ghcr.io/oxibelt/oxibelt:alpine-musl'
  ])
  Assert.equal(Plan.schemaVersion, 8)
  Assert.equal(Plan.sourceRef, 'refs/tags/5.2.0')
  Assert.equal(Plan.sourceDirty, 'clean')
  Assert.equal(Plan.buildKind, 'official_release')
  Assert.deepEqual(Plan.roles, [
    {
      role: 'standalone',
      image: 'ghcr.io/oxibelt/oxibelt',
      dockerTarget: 'standalone',
      binaries: ['oxibelt', 'oxibeltctl', 'oxibelt-keysigner', 'oxibelt-netport-switcher'],
      entrypoint: ['/usr/local/bin/oxibelt', '--config', '/etc/oxibelt/config/oxibelt.toml'],
      user: '10001:10001',
      ports: ['8443/tcp', '8443/udp'],
      embeddedAssets: ['admin-openapi', 'person-proof']
    },
    {
      role: 'dataplane',
      image: 'ghcr.io/oxibelt/oxibelt-dataplane',
      dockerTarget: 'dataplane',
      binaries: ['oxibelt'],
      entrypoint: ['/usr/local/bin/oxibelt', '--config', '/etc/oxibelt/config/oxibelt.toml'],
      user: '10001:10001',
      ports: ['8443/tcp', '8443/udp'],
      embeddedAssets: ['admin-openapi', 'person-proof']
    },
    {
      role: 'dataplane-strict',
      image: 'ghcr.io/oxibelt/oxibelt-dataplane-strict',
      dockerTarget: 'dataplane-strict',
      binaries: ['oxibelt-dataplane-strict'],
      entrypoint: ['/usr/local/bin/oxibelt-dataplane-strict', '--config', '/etc/oxibelt/config/oxibelt.toml'],
      user: '10001:10001',
      ports: ['8443/tcp', '8443/udp'],
      embeddedAssets: ['person-proof']
    },
    {
      role: 'controller',
      image: 'ghcr.io/oxibelt/oxibelt-gateway-controller',
      dockerTarget: 'controller',
      binaries: ['oxibelt-gateway-controller'],
      entrypoint: ['/usr/local/bin/oxibelt-gateway-controller'],
      user: '10001:10001',
      ports: [],
      embeddedAssets: []
    },
    {
      role: 'tools',
      image: 'ghcr.io/oxibelt/oxibelt-tools',
      dockerTarget: 'tools',
      binaries: ['oxibeltctl'],
      entrypoint: ['/usr/local/bin/oxibeltctl'],
      user: '10001:10001',
      ports: [],
      embeddedAssets: []
    },
    {
      role: 'keysigner',
      image: 'ghcr.io/oxibelt/oxibelt-keysigner',
      dockerTarget: 'keysigner',
      binaries: ['oxibelt-keysigner'],
      entrypoint: ['/usr/local/bin/oxibelt-keysigner'],
      user: '10002:10002',
      ports: [],
      embeddedAssets: []
    }
  ])
  Assert.equal('sbom' in Plan, false)
  Assert.equal('supplyChain' in Plan, false)
  Assert.equal('sbomArtifactName' in Amd64, false)
  Assert.equal('sbomFile' in Amd64, false)
})

test('image plan defines exact role-specific repositories, inventories, and artifacts', () => {
  const Plan = BuildImageReleasePlan({
    releaseTag: ParseReleaseTag('5.2.0'),
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    source: 'https://github.com/OxiBelt/OxiBelt'
  })

  Assert.equal(Plan.artifacts.length, 30)
  Assert.equal(Plan.manifests.length, 12)
  for (const Role of ['standalone', 'dataplane', 'dataplane-strict', 'controller', 'tools', 'keysigner'] as const) {
    AssertRepresentativeManifestArchs(Plan, Role)
    Assert.equal(Plan.artifacts.filter(Artifact => Artifact.role === Role).length, 5)
    Assert.equal(Plan.manifests.filter(Manifest => Manifest.role === Role).length, 2)
  }

  const Dataplane = Plan.artifacts.find(
    Artifact => Artifact.role === 'dataplane' && Artifact.artifactArch === 'amd64'
  )
  Assert.equal(Dataplane?.dockerTarget, 'dataplane')
  Assert.deepEqual(Dataplane?.binaries, ['oxibelt'])
  Assert.equal(
    Dataplane?.canonicalGhcrTag,
    'ghcr.io/oxibelt/oxibelt-dataplane:5.2.0-alpine-musl-amd64'
  )
  Assert.equal(Dataplane?.artifactName, 'oxibelt-dataplane-alpine-musl-amd64-image')

  const Strict = Plan.artifacts.find(
    Artifact => Artifact.role === 'dataplane-strict' && Artifact.artifactArch === 'amd64'
  )
  Assert.equal(Strict?.dockerTarget, 'dataplane-strict')
  Assert.deepEqual(Strict?.binaries, ['oxibelt-dataplane-strict'])
  Assert.deepEqual(Strict?.embeddedAssets, ['person-proof'])
  Assert.equal(
    Strict?.canonicalGhcrTag,
    'ghcr.io/oxibelt/oxibelt-dataplane-strict:5.2.0-alpine-musl-amd64'
  )
})

test('beta and build image plans use amd64 representative manifests', () => {
  for (const Tag of ['5.2.0-beta.1', '5.2.0-build.4f43abcd']) {
    const Plan = BuildImageReleasePlan({
      releaseTag: ParseReleaseTag(Tag),
      revision: '4f43abcd99999999999999999999999999999999',
      source: 'https://github.com/OxiBelt/OxiBelt'
    })

    AssertRepresentativeManifestArchs(Plan)
  }
})

test('beta and build image plans do not include latest or major aliases', () => {
  for (const Tag of ['5.2.0-beta.1', '5.2.0-build.4f43abcd']) {
    const Plan = BuildImageReleasePlan({
      releaseTag: ParseReleaseTag(Tag),
      revision: '4f43abcd99999999999999999999999999999999',
      source: 'https://github.com/OxiBelt/OxiBelt'
    })
    const Serialized = JSON.stringify(Plan)

    Assert.equal(Serialized.includes(':latest'), false)
    Assert.equal(Serialized.includes(':5-alpine-musl'), false)
  }
})
