{{- include "oxibelt.validateAutoscaling" . -}}
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "oxibelt.name" . }}
  labels:
{{ include "oxibelt.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "oxibelt.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- if .Values.autoscaling.activeRequests.enabled }}
  - type: Pods
    pods:
      metric:
        name: oxibelt_active_http_requests
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.activeRequests.targetAverageValue }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: Min
      policies:
      - type: Pods
        value: 1
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds }}
  {{- end }}
{{- end }}
