{{- if .Values.serviceAccount.create }}
{{- include "oxibelt.validateKubernetesServiceAccount" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oxibelt.serviceAccountName" . }}
  labels:
{{ include "oxibelt.labels" . | indent 4 }}
automountServiceAccountToken: false
{{- end }}
