{{- include "oxibelt.validateAdditionalServicePorts" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxibelt.name" . }}
  labels:
{{ include "oxibelt.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (ne .Values.service.type "ClusterIP") .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
{{ include "oxibelt.selectorLabels" . | indent 4 }}
  ports:
  {{- if .Values.service.ports.http.enabled }}
  - name: http
    port: {{ .Values.service.ports.http.port }}
    targetPort: http
    protocol: TCP
  {{- end }}
  {{- if .Values.service.ports.https.enabled }}
  - name: https
    port: {{ .Values.service.ports.https.port }}
    targetPort: https
    protocol: TCP
  {{- end }}
  {{- if .Values.service.ports.http3.enabled }}
  - name: http3
    port: {{ .Values.service.ports.http3.port }}
    targetPort: http3
    protocol: UDP
  {{- end }}
  {{- range $port := .Values.service.additionalPorts }}
  - name: {{ $port.name }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: {{ $port.protocol }}
  {{- end }}
