{{- include "oxibelt-gateway-controller.validateSecurity" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oxibelt-gateway-controller.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "oxibelt-gateway-controller.name" . }}
automountServiceAccountToken: false
