//! Runtime, listener, TLS, proxy, compression, and cache shape keys.

use super::super::*;

pub(super) fn allowed_keys(path: &str) -> Option<&'static [&'static str]> {
  let keys: &'static [&'static str] = match path {
    "" => allowed_keys::ROOT_CONFIG_KEYS,
    "access_log" => &["admin", "otlp", "stdout", "system", "waf"][..],
    "access_log.admin" => &["enabled"][..],
    "access_log.otlp" => &[
      "batch_size",
      "enabled",
      "endpoint",
      "export_timeout_ms",
      "queue_capacity",
      "schema",
      "service_name",
      "trusted_ca_certs",
    ][..],
    "access_log.stdout" => &["enabled", "schema"][..],
    "access_log.system" => &["enabled"][..],
    "access_log.waf" => &["enabled"][..],
    "config" => &[
      "lb_policy_compat_profile",
      "strict_unknown_fields",
      "warn_on_deprecated_fields",
    ][..],
    "logging" => &["access_log", "level"][..],
    "logging.access_log" => &["enabled", "fields", "stdout"][..],
    "logging.access_log.fields" => &["expression", "name", "value"][..],
    "runtime" => &[
      "accept",
      "direct_h1_io",
      "drain",
      "hardening",
      "hot_reload",
      "linux_only",
      "main_runtime",
      "memory_only_state",
      "netport_switcher",
      "read_only_rootfs_compatible",
      "topology_policy",
      "unprivileged_mode",
      "worker_multipliers",
      "worker_threads",
      "workers",
    ][..],
    "runtime.worker_multipliers" => &[
      "accept",
      "compio_direct_h1",
      "quic_socket",
      "runtime",
      "tokio",
    ][..],
    "runtime.workers" => &["compio_direct_h1", "tokio"][..],
    "runtime.accept" => &[
      "accept_error_backoff_ms",
      "backlog",
      "reuse_port",
      "workers",
    ][..],
    "runtime.drain" => &[
      "graceful_timeout_ms",
      "long_connection_close_delay_ms",
      "shutdown_delay_ms",
    ][..],
    "runtime.hot_reload" => &["mode", "poll_interval_ms"][..],
    "runtime.hardening" => &["close_range", "filesystem_manifest", "landlock", "seccomp"][..],
    "runtime.hardening.filesystem_manifest" => &["expected_digest", "expected_writable_paths"][..],
    "runtime.hardening.seccomp" => {
      &["expectation", "mode", "profile_digest", "profile_identity"][..]
    }
    "runtime.hardening.landlock" => &["mode", "read_paths", "read_write_paths"][..],
    "runtime.netport_switcher" => workers::NETPORT_SWITCHER_CONFIG_KEYS,
    "listeners" => &[
      "http1",
      "http2",
      "http3",
      "http_bind",
      "http_binds",
      "http_mode",
      "https_bind",
      "https_binds",
      "proxy_protocol",
    ][..],
    "listeners.proxy_protocol" => &["enabled", "trusted_sources", "version"][..],
    "client_identity" => client_identity::CLIENT_IDENTITY_CONFIG_KEYS,
    "client_identity.asn" => client_identity::CLIENT_IDENTITY_ASN_CONFIG_KEYS,
    "client_identity.asn.managed" => client_identity::CLIENT_IDENTITY_ASN_MANAGED_CONFIG_KEYS,
    "client_identity.asn.iana_registry" => {
      client_identity::CLIENT_IDENTITY_ASN_IANA_REGISTRY_CONFIG_KEYS
    }
    "crypto" => crypto::CRYPTO_CONFIG_KEYS,
    "crypto.primitives" => crypto::CRYPTO_PRIMITIVES_CONFIG_KEYS,
    "crypto.primitive_backends" => crypto::CRYPTO_PRIMITIVE_BACKENDS_CONFIG_KEYS,
    "sni_forward" => sni_forward::SNI_FORWARD_CONFIG_KEYS,
    "sni_forward.rules" => sni_forward::SNI_FORWARD_RULE_KEYS,
    "tls" => allowed_keys::TLS_CONFIG_KEYS,
    "tls.1_2" => allowed_keys::TLS12_NEGOTIATION_CONFIG_KEYS,
    "tls.1_3" => allowed_keys::TLS13_NEGOTIATION_CONFIG_KEYS,
    "tls.resumption" => allowed_keys::TLS_RESUMPTION_CONFIG_KEYS,
    "tls.remote_signer" => allowed_keys::TLS_REMOTE_SIGNER_CONFIG_KEYS,
    "tls.ocsp" => tls::OCSP_CONFIG_KEYS,
    "tls.certificates" => &[
      "cert_chain",
      "ocsp",
      "private_key",
      "remote_signer_key_id",
      "server_names",
    ][..],
    "tls.certificates.ocsp" => tls::OCSP_CONFIG_KEYS,
    "tls.crlite" => crlite::CRLITE_CONFIG_KEYS,
    "tls.crlite.managed" => crlite::CRLITE_MANAGED_CONFIG_KEYS,
    "tls.client_auth" => allowed_keys::TLS_CLIENT_AUTH_CONFIG_KEYS,
    "quic" => &[
      "alt_svc",
      "downstream",
      "host_key_file",
      "retry",
      "socket",
      "transport",
      "upstream",
      "upstream_pool",
      "zero_rtt",
    ][..],
    "quic.alt_svc" => &["enabled", "max_age_seconds", "persist", "port_overrides"][..],
    "quic.alt_svc.port_overrides" => &["advertised_port", "bind"][..],
    "quic.transport" => &[
      "datagram_receive_buffer_bytes",
      "datagram_send_buffer_bytes",
      "gso",
      "idle_timeout_ms",
      "initial_mtu",
      "keep_alive_interval_ms",
      "max_concurrent_bidi_streams",
      "max_concurrent_uni_streams",
      "max_udp_payload_size",
      "min_mtu",
      "mtu_discovery",
      "receive_window_bytes",
      "send_fairness",
      "send_window_bytes",
      "stream_receive_window_bytes",
    ][..],
    "quic.transport.mtu_discovery" => &[
      "black_hole_cooldown_ms",
      "enabled",
      "interval_ms",
      "minimum_change",
      "upper_bound",
    ][..],
    "quic.downstream" => &["transport"][..],
    "quic.downstream.transport" => &[
      "datagram_receive_buffer_bytes",
      "datagram_send_buffer_bytes",
      "gso",
      "idle_timeout_ms",
      "initial_mtu",
      "keep_alive_interval_ms",
      "max_concurrent_bidi_streams",
      "max_concurrent_uni_streams",
      "max_udp_payload_size",
      "min_mtu",
      "mtu_discovery",
      "receive_window_bytes",
      "send_fairness",
      "send_window_bytes",
      "stream_receive_window_bytes",
    ][..],
    "quic.downstream.transport.mtu_discovery" => &[
      "black_hole_cooldown_ms",
      "enabled",
      "interval_ms",
      "minimum_change",
      "upper_bound",
    ][..],
    "quic.upstream" => &["resolution", "transport"][..],
    "quic.upstream.resolution" => &[
      "address_family_stagger_ms",
      "cooldown_base_ms",
      "cooldown_max_ms",
      "max_connect_attempts",
      "max_endpoint_count",
      "max_ttl_ms",
      "min_ttl_ms",
      "negative_ttl_ms",
    ][..],
    "quic.upstream.transport" => &[
      "datagram_receive_buffer_bytes",
      "datagram_send_buffer_bytes",
      "gso",
      "idle_timeout_ms",
      "initial_mtu",
      "keep_alive_interval_ms",
      "max_concurrent_bidi_streams",
      "max_concurrent_uni_streams",
      "max_udp_payload_size",
      "min_mtu",
      "mtu_discovery",
      "receive_window_bytes",
      "send_fairness",
      "send_window_bytes",
      "stream_receive_window_bytes",
    ][..],
    "quic.upstream.transport.mtu_discovery" => &[
      "black_hole_cooldown_ms",
      "enabled",
      "interval_ms",
      "minimum_change",
      "upper_bound",
    ][..],
    "quic.socket" => &[
      "receive_buffer_bytes",
      "reuse_port",
      "send_buffer_bytes",
      "workers",
    ][..],
    "quic.upstream_pool" => &["enabled", "max_connections_per_upstream", "max_lifetime_ms"][..],
    "proxy" => &[
      "auto_upgrade",
      "buffering",
      "forwarded_headers",
      "grpc_web",
      "http",
      "http2",
      "http3",
      "real_ip",
      "retry",
      "static_files",
      "trusted_ca_certs",
      "upstream_revocation",
      "upgrades",
    ][..],
    "proxy.upstream_revocation" => outbound_revocation::OUTBOUND_REVOCATION_CONFIG_KEYS,
    "proxy.upstream_revocation.ocsp" => outbound_revocation::OUTBOUND_OCSP_CONFIG_KEYS,
    "proxy.upstream_revocation.crlite" => crlite::CRLITE_CONFIG_KEYS,
    "proxy.upstream_revocation.crlite.managed" => crlite::CRLITE_MANAGED_CONFIG_KEYS,
    "proxy.forwarded_headers" => &["client_ip_source", "mode"][..],
    "proxy.auto_upgrade" => &["enabled", "max_http_version"][..],
    "proxy.real_ip" => &[
      "enabled",
      "fail_on_untrusted_forwarded_headers",
      "header",
      "recursive",
      "trusted_proxies",
    ][..],
    "proxy.upgrades" => &["connect_tunneling", "generic_http_upgrade", "websocket"][..],
    "proxy.grpc_web" => &["enabled"][..],
    "proxy.retry" => &[
      "backoff_base_ms",
      "backoff_max_ms",
      "enabled",
      "exclude_failed_pool_upstreams",
      "jitter",
      "on",
      "per_attempt_timeout_ms",
      "report_passive_health",
      "reselect_pool_on_retry",
      "retry_non_idempotent",
      "timeout_ms",
      "total_budget_ms",
      "tries",
    ][..],
    "proxy.buffering" => &[
      "max_memory_body_bytes",
      "max_temp_file_bytes",
      "request",
      "response",
      "temp_dir",
    ][..],
    "proxy.http" => &[
      "early_hints",
      "trailers",
      "expect_continue",
      "priority",
      "sse_auto_streaming",
      "direct_h1_small_request_body_max_bytes",
      "grpc",
      "errors",
    ][..],
    "proxy.http2" => &[
      "adaptive_window",
      "initial_connection_window_bytes",
      "initial_stream_window_bytes",
      "keep_alive_interval_ms",
      "keep_alive_timeout_ms",
      "keep_alive_while_idle",
      "max_frame_size_bytes",
      "max_concurrent_streams",
      "max_send_buf_size",
    ][..],
    "proxy.http3" => &["inline_bodyless_fast_path"][..],
    "proxy.http.grpc" => &["enabled", "respect_grpc_timeout", "retry"][..],
    "proxy.http.errors" => &["mode"][..],
    "proxy.static_files" => &[
      "hot_object_cache_max_bytes",
      "hot_object_cache_max_file_bytes",
      "inline_max_bytes",
      "open_file_cache_max_entries",
      "open_file_cache_ttl_ms",
      "sendfile",
      "sendfile_chunk_bytes",
      "sendfile_write_strategy",
    ][..],
    "limits" => &[
      "client_body_timeout_ms",
      "client_header_timeout_ms",
      "client_idle_timeout_ms",
      "connection_limit_identity",
      "max_connections",
      "max_connections_per_ip",
      "max_webtransport_sessions",
      "max_webtransport_sessions_per_connection",
      "max_webtransport_sessions_per_ip",
      "max_header_name_bytes",
      "max_header_value_bytes",
      "max_headers",
      "max_request_body_bytes",
      "max_requests_per_connection",
      "max_total_header_bytes",
      "max_uri_bytes",
      "response_send_timeout_ms",
      "tls_handshake_timeout_ms",
      "websocket_idle_timeout_ms",
      "webtransport_idle_timeout_ms",
    ][..],
    "compression" => &[
      "br",
      "deflate",
      "enabled",
      "gzip",
      "level",
      "max_concurrent_responses",
      "mime_types",
      "min_size_bytes",
      "policies",
      "proxied",
      "statuses",
      "upstream_accept_encoding",
      "vary",
      "zstd",
    ][..],
    "compression.policies" => &[
      "br",
      "deflate",
      "enabled",
      "gzip",
      "level",
      "mime_types",
      "min_size_bytes",
      "name",
      "proxied",
      "statuses",
      "upstream_accept_encoding",
      "vary",
      "zstd",
    ][..],
    "cache" => &[
      "admission",
      "background_refresh",
      "background_refresh_max_concurrent",
      "bypass_request_headers",
      "cache_key",
      "cache_methods",
      "default_ttl_seconds",
      "disk_dir",
      "disk_max_size_bytes",
      "enabled",
      "external_handler",
      "external_handlers",
      "lock",
      "lock_wait_timeout_ms",
      "copy_file_range",
      "max_tag_bytes",
      "max_tags_per_entry",
      "max_vary_fields",
      "max_vary_variants_per_key",
      "max_size_bytes",
      "memory_auto_fraction",
      "memory_max_size_bytes",
      "negative_statuses",
      "negative_ttl_seconds",
      "partition_key",
      "policies",
      "respect_cache_control",
      "stale_if_error",
      "stale_if_error_seconds",
      "stale_while_revalidate_seconds",
      "store",
      "stream_chunk_bytes",
      "stream_large_objects",
      "surrogate",
      "tag_headers",
      "tmpfs_dir",
    ][..],
    "cache.admission" => &[
      "content_types",
      "max_body_bytes",
      "max_tracked_keys",
      "min_hits",
      "statuses",
    ][..],
    "cache.surrogate" => &["enabled", "strip_response_header"][..],
    "cache.external_handlers" => &[
      "connect_timeout_ms",
      "endpoint",
      "fail_policy",
      "kind",
      "max_body_bytes",
      "max_inflight_requests",
      "max_metadata_bytes",
      "name",
      "request_timeout_ms",
      "token_env",
    ][..],
    "cache.stale_if_error" => &[
      "connect_error",
      "max_upstream_stale_seconds",
      "read_timeout",
      "statuses",
    ][..],
    "cache.policies" => &[
      "admission",
      "background_refresh",
      "background_refresh_max_concurrent",
      "cache_key",
      "default_ttl_seconds",
      "disk_max_size_bytes",
      "external_handler",
      "lock_wait_timeout_ms",
      "max_tag_bytes",
      "max_tags_per_entry",
      "max_vary_fields",
      "max_vary_variants_per_key",
      "memory_max_size_bytes",
      "name",
      "negative_statuses",
      "negative_ttl_seconds",
      "partition_key",
      "rules",
      "stale_if_error",
      "store",
      "tag_headers",
    ][..],
    "cache.policies.admission" => &[
      "content_types",
      "max_body_bytes",
      "max_tracked_keys",
      "min_hits",
      "statuses",
    ][..],
    "cache.policies.stale_if_error" => &[
      "connect_error",
      "max_upstream_stale_seconds",
      "read_timeout",
      "statuses",
    ][..],
    "cache.policies.rules" => &["mime_types", "store"][..],
    _ => return None,
  };
  Some(keys)
}
