//! Upstream, route, stream, TURN, and limit shape keys.

use super::super::*;

pub(super) fn allowed_keys(path: &str) -> Option<&'static [&'static str]> {
  let keys: &'static [&'static str] = match path {
    "upstreams" => &[
      "connect_timeout_ms",
      "first_byte_timeout_ms",
      "idle_timeout_ms",
      "max_http_version",
      "happy_eyeballs_mode",
      "svcb_allowed_ports",
      "name",
      "origin",
      "pool_max_idle_per_host",
      "preserve_host",
      "proxy_protocol_egress",
      "read_timeout_ms",
      "request_timeout_ms",
      "send_timeout_ms",
      "tls",
      "webrtc",
      "websocket",
      "webtransport",
    ][..],
    "upstreams.tls" | "upstream_pools.servers.tls" | "upstream_pools.discovery.tls" => &[
      "ech",
      "resumption",
      "server_name",
      "subject_alt_names",
      "trust",
      "trusted_ca_certs",
      "trusted_ca_sha256",
      "upstream_revocation",
    ][..],
    "upstreams.tls.ech" | "upstream_pools.servers.tls.ech" | "upstream_pools.discovery.tls.ech" => {
      &["config_list_file", "mode"][..]
    }
    "upstreams.tls.resumption"
    | "upstream_pools.servers.tls.resumption"
    | "upstream_pools.discovery.tls.resumption" => &["mode", "session_cache_size", "tls12"][..],
    "upstreams.tls.subject_alt_names"
    | "upstream_pools.servers.tls.subject_alt_names"
    | "upstream_pools.discovery.tls.subject_alt_names" => &["type", "value"][..],
    "upstreams.tls.upstream_revocation" => outbound_revocation::OUTBOUND_REVOCATION_CONFIG_KEYS,
    "upstreams.tls.upstream_revocation.ocsp" => outbound_revocation::OUTBOUND_OCSP_CONFIG_KEYS,
    "upstreams.tls.upstream_revocation.crlite" => crlite::CRLITE_CONFIG_KEYS,
    "upstreams.tls.upstream_revocation.crlite.managed" => crlite::CRLITE_MANAGED_CONFIG_KEYS,
    "upstream_pools" => &[
      "algorithm",
      "discovery",
      "hash_key",
      "health_check",
      "keepalive",
      "name",
      "outlier_ejection",
      "servers",
      "slow_start",
      "sticky_cookie",
      "circuit_breaker",
    ][..],
    "upstream_pools.discovery" => &[
      "datacenter",
      "endpoint",
      "file",
      "filter",
      "id",
      "key_prefix",
      "kubernetes_resource",
      "min_ttl_ms",
      "name",
      "namespace",
      "port",
      "port_name",
      "provider",
      "record_type",
      "refresh_interval_ms",
      "scheme",
      "service",
      "token_env",
      "token_file",
      "tls",
      "update_debounce_ms",
      "watch",
      "watch_timeout_seconds",
      "weight_multiplier",
    ][..],
    "upstream_pools.sticky_cookie" => &[
      "cookie_name",
      "fallback_algorithm",
      "http_only",
      "path",
      "same_site",
      "secret_env",
      "secure",
      "ttl_seconds",
    ][..],
    "upstream_pools.keepalive" => &["idle_timeout_ms", "max_idle", "max_lifetime_ms"][..],
    "upstream_pools.slow_start" => &["duration_ms", "enabled", "min_weight_percent"][..],
    "upstream_pools.outlier_ejection" => &[
      "base_ejection_ms",
      "consecutive_failures",
      "enabled",
      "max_ejection_ms",
    ][..],
    "upstream_pools.health_check" => &[
      "body",
      "body_match_max_bytes",
      "enabled",
      "expected_body_regex",
      "expected_status",
      "expected_status_ranges",
      "fall",
      "grpc_expected_statuses",
      "grpc_service",
      "health_host",
      "health_port",
      "headers",
      "healthy_threshold",
      "interval_ms",
      "jitter_ms",
      "method",
      "mode",
      "path",
      "protocol",
      "rise",
      "timeout_ms",
      "tls",
      "unhealthy_threshold",
    ][..],
    "upstream_pools.health_check.headers" => &["name", "value"][..],
    "upstream_pools.health_check.expected_status_ranges" => &["end", "start"][..],
    "upstream_pools.health_check.tls" => &["trusted_ca_certs", "upstream_revocation"][..],
    "upstream_pools.health_check.tls.upstream_revocation" => {
      outbound_revocation::OUTBOUND_REVOCATION_CONFIG_KEYS
    }
    "upstream_pools.health_check.tls.upstream_revocation.ocsp" => {
      outbound_revocation::OUTBOUND_OCSP_CONFIG_KEYS
    }
    "upstream_pools.health_check.tls.upstream_revocation.crlite" => crlite::CRLITE_CONFIG_KEYS,
    "upstream_pools.health_check.tls.upstream_revocation.crlite.managed" => {
      crlite::CRLITE_MANAGED_CONFIG_KEYS
    }
    "upstream_pools.servers" => &[
      "backup",
      "id",
      "max_conns",
      "origin",
      "state",
      "tls",
      "weight",
    ][..],
    "upstream_pools.circuit_breaker" | "routes.circuit_breaker" => &[
      "max_active_requests",
      "max_pending_requests",
      "pending_queue_timeout_ms",
      "pending_queue_timeout",
      "max_connections",
      "max_streams",
      "max_body_inspection_jobs",
      "max_decompression_jobs",
    ][..],
    "routes" => &[
      "actions",
      "buffering",
      "cache",
      "ct_log",
      "ct_surface",
      "compression",
      "hosts",
      "match",
      "name",
      "path_prefix",
      "replace_prefix_with",
      "retry",
      "circuit_breaker",
      "security_headers",
      "priority_class",
      "connect_tunneling",
      "generic_http_upgrade",
      "grpc_web",
      "external_auth",
      "ipm",
      "limits",
      "static_root",
      "static_files",
      "tls",
      "upstream",
      "upstream_http_version",
      "upstream_http_version_mode",
      "upstream_pool",
      "timeouts",
      "waf",
    ][..],
    "routes.actions" => &[
      "cors",
      "redirect",
      "request_headers",
      "request_mirrors",
      "response_headers",
      "rewrite",
    ][..],
    "routes.actions.cors" => &[
      "allow_credentials",
      "allow_headers",
      "allow_methods",
      "allow_origins",
      "expose_headers",
      "max_age_seconds",
    ][..],
    "routes.actions.redirect" => &[
      "hostname",
      "location_template",
      "path",
      "port",
      "scheme",
      "status",
    ][..],
    "routes.actions.request_headers" => &["add", "remove", "set"][..],
    "routes.actions.request_headers.add" => &["name", "value"][..],
    "routes.actions.request_headers.set" => &["name", "value"][..],
    "routes.actions.request_mirrors" => &["max_body_bytes", "sample_percent", "upstream_pool"][..],
    "routes.actions.response_headers" => &["add", "remove", "set"][..],
    "routes.actions.response_headers.add" => &["name", "value"][..],
    "routes.actions.response_headers.set" => &["name", "value"][..],
    "routes.actions.rewrite" => &["authority", "path", "query"][..],
    "routes.static_files" => &[
      "cache_control",
      "cache_control_by_extension",
      "directory_index",
      "error_pages",
      "mime_overrides",
      "precompressed",
      "spa_fallback",
      "try_files",
    ][..],
    "routes.static_files.error_pages" => &["not_found", "server_error"][..],
    "routes.tls" => &["1_2", "1_3", "max_version", "min_version", "ssl_early_data"][..],
    "routes.tls.1_2" => allowed_keys::TLS12_NEGOTIATION_CONFIG_KEYS,
    "routes.tls.1_3" => allowed_keys::TLS13_NEGOTIATION_CONFIG_KEYS,
    "routes.match" => &[
      "headers",
      "methods",
      "path",
      "priority",
      "protocols",
      "queries",
      "source_cidrs",
      "terminal",
      "tls",
    ][..],
    "routes.match.headers" => &[
      "contains", "exact", "name", "prefix", "present", "regex", "suffix",
    ][..],
    "routes.match.queries" => &[
      "contains", "exact", "name", "prefix", "present", "regex", "suffix",
    ][..],
    "routes.match.path" => &["exact", "prefix", "regex"][..],
    "routes.match.tls" => &["client_cert"][..],
    "routes.match.tls.client_cert" => &[
      "fingerprint_sha256",
      "present",
      "san_dns",
      "san_ip",
      "subject_cn",
    ][..],
    "routes.match.tls.client_cert.fingerprint_sha256" => {
      &["contains", "exact", "prefix", "present", "regex", "suffix"][..]
    }
    "routes.match.tls.client_cert.san_dns" => {
      &["contains", "exact", "prefix", "present", "regex", "suffix"][..]
    }
    "routes.match.tls.client_cert.san_ip" => {
      &["contains", "exact", "prefix", "present", "regex", "suffix"][..]
    }
    "routes.match.tls.client_cert.subject_cn" => {
      &["contains", "exact", "prefix", "present", "regex", "suffix"][..]
    }
    "routes.buffering" => &[
      "max_memory_body_bytes",
      "max_temp_file_bytes",
      "request",
      "response",
    ][..],
    "routes.limits" => &["max_request_body_bytes"][..],
    "routes.timeouts" => &[
      "client_body_timeout_ms",
      "response_send_timeout_ms",
      "upstream_connect_timeout_ms",
      "upstream_first_byte_timeout_ms",
      "upstream_read_timeout_ms",
      "upstream_request_timeout_ms",
      "upstream_send_timeout_ms",
      "websocket_idle_timeout_ms",
      "webtransport_idle_timeout_ms",
    ][..],
    "routes.ipm" => &["action", "enabled"][..],
    "routes.retry" => &[
      "backoff_base_ms",
      "backoff_max_ms",
      "enabled",
      "exclude_failed_pool_upstreams",
      "jitter",
      "on",
      "per_attempt_timeout_ms",
      "report_passive_health",
      "reselect_pool_on_retry",
      "retry_non_idempotent",
      "total_budget_ms",
      "tries",
    ][..],
    "stream_listeners" => &[
      "bind",
      "connect_timeout_ms",
      "idle_timeout_ms",
      "max_udp_flows",
      "name",
      "network",
      "proxy_protocol_egress",
      "sni_rules",
      "target",
      "udp_datagram_burst",
      "udp_datagram_rate",
      "udp_batch",
      "udp_batch_size",
      "udp_flow_state",
      "udp_new_flow_burst",
      "udp_new_flow_rate",
      "upstream_pool",
    ][..],
    "stream_listeners.sni_rules" => &[
      "connect_timeout_ms",
      "idle_timeout_ms",
      "name",
      "proxy_protocol_egress",
      "server_names",
      "target",
      "upstream_pool",
    ][..],
    "stream_upstream_pools" => &["algorithm", "hash_key", "name", "servers"][..],
    "stream_upstream_pools.servers" => {
      &["backup", "id", "max_conns", "origin", "state", "weight"][..]
    }
    "turn_upstream_pools" => &["algorithm", "hash_key", "health_check", "name", "servers"][..],
    "turn_upstream_pools.health_check" => &[
      "enabled",
      "healthy_threshold",
      "interval_ms",
      "timeout_ms",
      "unhealthy_threshold",
    ][..],
    "turn_upstream_pools.servers" => {
      &["backup", "id", "max_conns", "origin", "state", "weight"][..]
    }
    "webrtc_turn_listeners" => &[
      "auth",
      "bind_tcp",
      "bind_tls",
      "bind_udp",
      "idle_timeout_ms",
      "limits",
      "mode",
      "name",
      "peer_policy",
      "public_ip",
      "realm",
      "relay_bind_ip",
      "relay_families",
      "relay_port_range",
      "stream_outbound_queue_capacity",
      "tcp_pool",
      "tls",
      "tls_pool",
      "udp_pool",
    ][..],
    "webrtc_turn_listeners.auth" => &[
      "mode",
      "nonce_ttl_seconds",
      "rest_shared_secret",
      "rest_shared_secret_env",
      "static_credentials",
    ][..],
    "webrtc_turn_listeners.auth.static_credentials" => {
      &["password", "password_env", "username"][..]
    }
    "webrtc_turn_listeners.limits" => &[
      "max_allocation_lifetime_seconds",
      "max_allocations_per_client",
      "max_allocations_per_listener",
      "max_channels_per_allocation",
      "max_permissions_per_allocation",
    ][..],
    "webrtc_turn_listeners.peer_policy" => &[
      "allow_link_local_peers",
      "allow_loopback_peers",
      "allow_multicast_peers",
      "allow_private_peers",
      "allow_unspecified_peers",
    ][..],
    "webrtc_turn_listeners.relay_families" => {
      &["family", "public_ip", "relay_bind_ip", "relay_port_range"][..]
    }
    "webrtc_turn_listeners.relay_families.relay_port_range" => &["end", "start"][..],
    "webrtc_turn_listeners.relay_port_range" => &["end", "start"][..],
    "webrtc_turn_listeners.tls" => &[
      "cert_chain",
      "private_key",
      "remote_signer_key_id",
      "resumption",
    ][..],
    "webrtc_turn_listeners.tls.resumption" => &[
      "mode",
      "rotation_seconds",
      "session_cache_size",
      "tls13_ticket_count",
    ][..],
    "rate_limits" => &[
      "access_token_source",
      "burst",
      "identity_parts",
      "ipv4_prefix_bits",
      "ipv6_prefix_bits",
      "key",
      "max_buckets",
      "mode",
      "name",
      "rate",
      "routes",
      "status",
      "token_header",
      "token_bindings",
    ][..],
    "connection_limits" => &["key", "limit", "name", "status"][..],
    _ => return None,
  };
  Some(keys)
}
