//! Admin, identity, observability, policy, and shared-state shape keys.

use super::super::*;

pub(super) fn allowed_keys(path: &str) -> Option<&'static [&'static str]> {
  let keys: &'static [&'static str] = match path {
    "admin" => allowed_keys::ADMIN_CONFIG_KEYS,
    "admin.audit" => allowed_keys::ADMIN_AUDIT_CONFIG_KEYS,
    "admin.audit.store" => &["backend", "enabled", "kind"][..],
    "admin.audit.export" => &["enabled", "required_sinks", "sinks"][..],
    "admin.audit.spool" => allowed_keys::ADMIN_AUDIT_SPOOL_CONFIG_KEYS,
    "admin.audit.integrity" => allowed_keys::ADMIN_AUDIT_INTEGRITY_CONFIG_KEYS,
    "admin.audit.anchor" => allowed_keys::ADMIN_AUDIT_ANCHOR_CONFIG_KEYS,
    "admin.audit.anchor.sink" => allowed_keys::ADMIN_AUDIT_ANCHOR_SINK_CONFIG_KEYS,
    "admin.audit.anchor.signer" => allowed_keys::ADMIN_AUDIT_ANCHOR_SIGNER_CONFIG_KEYS,
    "admin.operations" => &[
      "artifact_key_env",
      "artifact_max_bytes",
      "backend",
      "checkpoint_max_bytes",
      "enabled",
      "event_buffer",
      "lease_renew_seconds",
      "lease_seconds",
      "max_lifetime_seconds",
      "max_queued",
      "max_running",
      "max_stored",
      "persistence",
      "result_max_bytes",
      "retention_seconds",
      "webtransport",
      "webtransport_max_sessions",
      "websocket",
    ][..],
    "admin.mutations" => allowed_keys::ADMIN_MUTATIONS_CONFIG_KEYS,
    "admin.mutations.rollout" => allowed_keys::ADMIN_MUTATION_ROLLOUT_CONFIG_KEYS,
    "admin.mutations.signers" => allowed_keys::ADMIN_MUTATION_SIGNER_CONFIG_KEYS,
    "admin.http3" => &["bind", "enabled"][..],
    "admin.cache_purge_signing" => &[
      "enabled",
      "key_env",
      "max_skew_seconds",
      "nonce_ttl_seconds",
    ][..],
    "admin.workload_identity" => allowed_keys::ADMIN_WORKLOAD_IDENTITY_CONFIG_KEYS,
    "admin.rbac" => &["tokens"][..],
    "admin.rbac.tokens" => &[
      "bearer_token_env",
      "deny_permissions",
      "name",
      "permissions",
      "roles",
    ][..],
    "admin.token_store" => &[
      "audience",
      "backend",
      "enabled",
      "fail_closed",
      "issuer",
      "public_key_env",
      "snapshot_refresh_interval_ms",
      "token_ttl_seconds",
    ][..],
    "ipm" => &[
      "bindings",
      "backend",
      "credentials",
      "enabled",
      "fail_closed",
      "break_glass",
      "namespace",
      "policies",
      "principals",
      "trust",
    ][..],
    "ipm.break_glass" => allowed_keys::IPM_BREAK_GLASS_CONFIG_KEYS,
    "ipm.credentials" => &[
      "bearer_token_env",
      "break_glass_access_token_hash",
      "name",
      "principal",
    ][..],
    "ipm.principals" => &["groups", "id", "subject"][..],
    "ipm.policies" => &["name", "statements", "version"][..],
    "ipm.policies.statements" => &["actions", "conditions", "effect", "resources"][..],
    "ipm.policies.statements.conditions" => &["key", "operator", "values"][..],
    "ipm.bindings" => &["group", "policy", "principal"][..],
    "ipm.trust" => &["claim", "group", "principal", "source", "value"][..],
    "admin.tls" => &[
      "certificates",
      "client_auth",
      "enabled",
      "max_version",
      "min_version",
      "reject_unknown_sni",
      "require_sni",
      "resumption",
      "session_ticket_rotation_seconds",
      "session_tickets",
    ][..],
    "admin.tls.resumption" => &[
      "mode",
      "rotation_seconds",
      "session_cache_size",
      "tls13_ticket_count",
    ][..],
    "admin.tls.certificates" => &["cert_chain", "default", "private_key", "server_names"][..],
    "admin.tls.client_auth" => &["ca_certs", "mode", "verify_depth"][..],
    "metrics" => &[
      "bind",
      "detail",
      "enabled",
      "format",
      "histogram_buckets_ms",
    ][..],
    "overload" => &[
      "enabled",
      "sample_interval_ms",
      "sample_interval",
      "soft_enter_samples",
      "recovery_samples",
      "recovery_ratio",
      "signal_stale_timeout_ms",
      "thresholds",
      "actions",
      "reserved_capacity",
    ][..],
    "overload.thresholds" => &[
      "memory_soft_ratio",
      "memory_hard_ratio",
      "fd_soft_ratio",
      "fd_hard_ratio",
      "cpu_soft_ratio",
      "cpu_hard_ratio",
      "event_loop_lag_soft_ms",
      "event_loop_lag_hard_ms",
      "event_loop_lag_soft",
      "event_loop_lag_hard",
      "shared_state_waiters_soft",
      "shared_state_waiters_hard",
      "downstream_connections_soft",
      "downstream_connections_hard",
      "active_requests_soft",
      "active_requests_hard",
      "h2_streams_soft",
      "h2_streams_hard",
      "h3_streams_soft",
      "h3_streams_hard",
      "pending_upstream_requests_soft",
      "pending_upstream_requests_hard",
      "retry_concurrency_soft",
      "retry_concurrency_hard",
      "cache_fill_concurrency_soft",
      "cache_fill_concurrency_hard",
      "waf_body_inspection_concurrency_soft",
      "waf_body_inspection_concurrency_hard",
      "compression_jobs_soft",
      "compression_jobs_hard",
      "decompression_jobs_soft",
      "decompression_jobs_hard",
      "request_body_buffered_bytes_soft",
      "request_body_buffered_bytes_hard",
    ][..],
    "overload.actions" => &["soft", "hard"][..],
    "overload.actions.soft" => &[
      "disable_cache_fill",
      "compression_level_cap",
      "reject_priority_classes",
      "retry_budget_multiplier",
      "waf_body_inspection_concurrency_cap",
      "decompression_concurrency_cap",
      "prefer_cached_or_stale",
    ][..],
    "overload.actions.hard" => &[
      "reject_new_connections",
      "reject_new_streams",
      "reject_new_requests",
      "stop_large_request_bodies",
      "large_request_body_threshold_bytes",
      "disable_cache_fill",
      "disable_compression",
      "disable_retries",
      "disable_request_mirroring",
      "reject_expensive_waf_bodies",
      "enter_recoverable_drain",
      "fail_readiness",
      "response_status",
      "retry_after_seconds",
      "retry_after",
    ][..],
    "overload.reserved_capacity" => &[
      "file_descriptors",
      "admin_connections",
      "admin_requests",
      "health_connections",
      "health_requests",
      "metrics_connections",
      "metrics_requests",
    ][..],
    "circuit_breakers" => &[
      "enabled",
      "response_status",
      "capacity_retry_after_ms",
      "capacity_retry_after",
      "global",
      "route_defaults",
      "pool_defaults",
      "retry_budget",
      "failure",
      "priority",
    ][..],
    "circuit_breakers.global"
    | "circuit_breakers.route_defaults"
    | "circuit_breakers.pool_defaults" => &[
      "max_active_requests",
      "max_pending_requests",
      "pending_queue_timeout_ms",
      "pending_queue_timeout",
      "max_connections",
      "max_streams",
      "max_body_inspection_jobs",
      "max_decompression_jobs",
    ][..],
    "circuit_breakers.retry_budget" => &[
      "percent",
      "min_concurrency",
      "max_concurrency",
      "max_queue",
      "queue_timeout_ms",
      "queue_timeout",
    ][..],
    "circuit_breakers.priority" => &["enabled", "classes"][..],
    "circuit_breakers.priority.classes" => &[
      "name",
      "reserved_requests",
      "max_share",
      "max_pending_requests",
      "pending_queue_timeout_ms",
      "pending_queue_timeout",
      "rejection_policy",
    ][..],
    "circuit_breakers.failure" => &[
      "enabled",
      "on",
      "consecutive_failures",
      "minimum_requests",
      "failure_ratio",
      "window_ms",
      "window",
      "open_timeout_ms",
      "open_timeout",
      "max_open_timeout_ms",
      "max_open_timeout",
      "half_open_max_probes",
      "half_open_successes",
    ][..],
    "telemetry" => &["tracing"][..],
    "telemetry.tracing" => &[
      "enabled",
      "endpoint",
      "export_timeout_ms",
      "propagate_trace_context",
      "sample_ratio",
      "service_name",
    ][..],
    "health" => &["bind", "enabled", "live_path", "ready_path"][..],
    "security" => &["header_policies", "headers"][..],
    "security.headers" => &[
      "hsts",
      "hsts_include_subdomains",
      "hsts_max_age_seconds",
      "hsts_preload",
      "permissions_policy",
      "referrer_policy",
      "x_content_type_options",
    ][..],
    "security.header_policies" => &[
      "hsts",
      "hsts_include_subdomains",
      "hsts_max_age_seconds",
      "hsts_preload",
      "name",
      "permissions_policy",
      "referrer_policy",
      "x_content_type_options",
    ][..],
    "database" => &["mitigation"][..],
    "database.mitigation" => &[
      "backend",
      "connect_timeout_ms",
      "connection_url",
      "connection_url_env",
      "dedupe_window_ms",
      "enabled",
      "failure_policy",
      "max_connections",
      "mode",
      "namespace",
      "queue_capacity",
      "table",
      "tls",
      "ttl_seconds",
    ][..],
    "database.mitigation.tls" => &["ca_cert", "client_cert", "client_key", "mode"][..],
    "dynamic_policy" => &[
      "automation_api",
      "backend",
      "default_body",
      "default_status",
      "enabled",
      "fail_policy",
      "matching",
      "max_policies",
      "refresh_interval_ms",
    ][..],
    "dynamic_policy.automation_api" => &[
      "default_source_quota",
      "enabled",
      "require_ttl",
      "signature_key_env",
      "source_quotas",
    ][..],
    "dynamic_policy.automation_api.source_quotas" => &["max_active_policies", "source"][..],
    "dynamic_policy.matching" => &[
      "composite_identity_parts",
      "ipv4_prefix_bits",
      "ipv6_prefix_bits",
      "normalize_path",
      "token_bindings",
      "trust_route_name",
    ][..],
    "external_auth" => &[
      "allowed_content_types",
      "claim_headers",
      "client_id_env",
      "client_secret_env",
      "endpoint",
      "fail_policy",
      "forward_headers",
      "identity_headers",
      "max_response_body_bytes",
      "max_request_body_bytes",
      "name",
      "provider",
      "required_claims",
      "required_scopes",
      "terminal_response_headers",
      "timeout_ms",
    ][..],
    "external_auth.required_claims" => &["name", "value"][..],
    "external_auth.claim_headers" => &["claim", "header"][..],
    "shared_state" => &[
      "backends",
      "cache_backend",
      "cache_lock_ms",
      "connection_lease_ms",
      "connection_limits_backend",
      "default_backend",
      "dynamic_policy_backend",
      "enabled",
      "enumeration_max_items_per_operation",
      "enumeration_page_size",
      "failure_policies",
      "instance_id_env",
      "namespace",
      "operation_timeout_ms",
      "admin_tokens_backend",
      "person_proof_backend",
      "redis_plaintext_policy",
      "rate_limits_backend",
      "reload_backend",
      "sticky_sessions_backend",
      "udp_flow_identity_key_env",
      "udp_flows_backend",
      "upstream_health_backend",
    ][..],
    "shared_state.failure_policies" => &[
      "cache",
      "connection_limits",
      "person_proof",
      "rate_limits",
      "reload",
      "sticky_sessions",
      "udp_flows",
      "upstream_health",
    ][..],
    "shared_state.backends" => &[
      "connect_timeout_ms",
      "connection_url",
      "connection_url_env",
      "kind",
      "max_connections",
      "name",
      "redis_auth",
      "redis_pool",
      "redis_tls",
      "tls",
    ][..],
    "shared_state.backends.redis_pool" => &[
      "circuit_breaker_failure_threshold",
      "circuit_breaker_open_timeout_ms",
      "command_timeout_ms",
      "health_check_interval_ms",
      "idle_timeout_ms",
      "max_waiters",
      "min_idle_connections",
      "pool_wait_timeout_ms",
      "reconnect_max_backoff_ms",
      "reconnect_min_backoff_ms",
    ][..],
    "shared_state.backends.redis_tls" => &[
      "ca_cert",
      "client_cert",
      "client_key",
      "server_name",
      "server_spki_sha256",
      "trust_store",
    ][..],
    "shared_state.backends.redis_auth" => &["password_file", "username_file"][..],
    "shared_state.backends.tls" => &["ca_cert", "client_cert", "client_key", "mode"][..],
    _ => return None,
  };
  Some(keys)
}
