packages:
  - "devops"
  - "ui/*"
registry: "https://registry.npmjs.org/"
blockExoticSubdeps: true
trustLockfile: false
strictDepBuilds: true
minimumReleaseAge: 1440
auditConfig:
  ignoreGhsas: []
allowBuilds:
  "esbuild@0.28.2": true
