mod cache;
mod config_runtime;
mod ops;
mod protocol;
mod proxy;
mod security;
mod state_data;
mod waf;

pub(crate) fn docker_cases() -> Vec<crate::DockerCase> {
  let mut cases = Vec::new();
  cases.extend(config_runtime::docker_cases());
  cases.extend(proxy::docker_cases());
  cases.extend(protocol::docker_cases());
  cases.extend(waf::docker_cases());
  cases.extend(cache::docker_cases());
  cases.extend(state_data::docker_cases());
  cases.extend(ops::docker_cases());
  cases.extend(security::docker_cases());

  let mut ordered = Vec::with_capacity(CASE_ORDER.len());
  for (category, name) in CASE_ORDER {
    let index = cases
      .iter()
      .position(|case| case.category == *category && case.name == *name)
      .unwrap_or_else(|| panic!("missing Docker case {category}/{name}"));
    ordered.push(cases.remove(index));
  }
  assert!(
    cases.is_empty(),
    "unexpected Docker cases outside CASE_ORDER"
  );
  ordered
}

const CASE_ORDER: &[(&str, &str)] = &[
  ("config-valid", "minimal-http1"),
  ("config-valid", "edge-secure-medium-v1"),
  ("config-valid", "modular-include-glob"),
  ("config-valid", "multi-listener-binds"),
  ("config-valid", "root-netport-switcher-https-443"),
  ("config-valid", "static-ocsp-compression-off"),
  ("config-valid", "static-only-route-startup"),
  ("proxy-compression", "downstream-gzip-response"),
  ("proxy-compression", "secret-bearing-response-skip"),
  (
    "proxy-compression",
    "route-compression-off-overrides-default",
  ),
  ("proxy-compression", "proxied-vary-and-upstream-encoding"),
  ("config-valid", "https-grease-trusted-ca"),
  ("http-semantics", "early-hints-pass"),
  ("http-semantics", "expect-priority"),
  ("http-semantics", "sse-grpc-errors"),
  ("security", "hardened-default-seccomp-runtime"),
  ("security", "external-auth-response-body-timeout"),
  ("security", "external-auth-forwarded-uri"),
  ("security", "grpc-timeout-pool-health"),
  ("security", "fast-general-proxy-equivalence"),
  ("security", "static-openat2-blocking-isolated"),
  ("security", "static-file-symlink-race"),
  ("security", "static-hot-cache-security"),
  ("security", "static-sendfile-general-equivalence"),
  ("security", "static-sendfile-real-ip-waf"),
  ("security", "static-sendfile-response-timeout"),
  ("security", "connection-task-registry-reaping"),
  ("security", "tls-stateful-resumption-cache-bounded"),
  ("security", "dpi-bypass-clienthello-fragmentation"),
  ("security", "webtransport-session-limit"),
  ("security", "webtransport-real-ip-connection-limit"),
  ("security", "websocket-stream-waf-frame-limit"),
  ("security", "turn-udp-session-cleanup"),
  ("security", "webrtc-turn-auth-transports"),
  ("config-invalid", "strict-unknown-field"),
  ("config-invalid", "emit-mitigation-udf-payload-exclusion"),
  ("listener-http", "redirect-to-https"),
  ("listener-http", "plain-proxy-mode"),
  ("ops", "metrics-and-health"),
  ("ops", "observability-detail"),
  ("ops", "admin-config-file-sync"),
  ("ops", "admin-operation-webtransport"),
  ("ops", "kernel-extension-installer"),
  ("ops", "admin-audit-export-only-stdout"),
  ("ops", "system-access-log-stdout"),
  ("ops", "system-access-log-stdout-ecs"),
  ("ops", "system-access-log-otlp-ecs"),
  ("limits", "request-body-limit"),
  ("limits", "route-request-body-limit"),
  ("limits", "http3-content-length-zero-body-limit"),
  ("limits", "rate-limit-bucket-cap"),
  ("buffering", "request-spool"),
  ("buffering", "response-spool"),
  ("timeouts", "route-first-byte-timeout"),
  ("timeouts", "route-client-body-timeout"),
  ("timeouts", "zero-length-body-timeout"),
  ("timeouts", "route-upstream-read-timeout"),
  ("timeouts", "route-upstream-send-timeout"),
  ("proxy-identity", "real-ip-waf"),
  ("proxy-identity", "connection-limit-first-request-real-ip"),
  ("proxy-identity", "connection-limit-per-request-real-ip"),
  (
    "proxy-identity",
    "connection-limit-per-request-real-ip-http1-tunnels",
  ),
  ("proxy-protocol", "trusted-v1"),
  ("proxy-protocol", "connection-limit-source-ip"),
  ("protocol-operations", "generic-upgrade"),
  ("protocol-operations", "websocket-upgrade-echo"),
  ("protocol-operations", "connect-tunnel"),
  ("protocol-operations", "stream-listener"),
  ("protocol-operations", "proxy-protocol-egress-v1"),
  ("protocol-operations", "grpc-web-h2c"),
  ("protocol-operations", "grpc-active-health"),
  ("upstream-pools", "power-of-two-choices"),
  ("upstream-pools", "active-health-options"),
  ("upstream-pools", "retry-failover"),
  ("upstream-pools", "retry-storm-budget"),
  ("upstream-pools", "retry-connect-error-on-policy"),
  ("upstream-pools", "route-retry-enable"),
  ("upstream-pools", "slow-start-outlier-metrics"),
  ("upstream-pools", "route-retry-disable"),
  ("upstream-pools", "retry-non-idempotent"),
  ("upstream-discovery", "file-provider"),
  ("upstream-discovery", "dns-spoofed-answers"),
  ("upstream-discovery", "kubernetes-endpointslice-watch"),
  ("upstream-discovery", "nomad-service-watch"),
  ("upstream-discovery", "admin-runtime-control"),
  ("upstream-discovery", "admin-rbac"),
  ("cache", "tmpfs-route-cache"),
  ("cache", "route-named-cache-policy-isolated"),
  ("cache", "http-semantics-revalidate"),
  ("cache", "vary-header-isolation"),
  ("cache", "rfc9111-semantics"),
  ("cache", "range-hit"),
  ("cache", "multi-range-hit"),
  ("cache", "memory-then-disk-fallback"),
  ("cache", "disk-policy-by-mime"),
  ("cache", "admin-purge-tls-sni"),
  ("cache", "admin-purge-docker-plaintext-allowlist"),
  ("cache", "purge-audit"),
  ("cache", "tag-purge"),
  ("cache", "signed-purge"),
  ("cache", "tenant-partition-isolation"),
  ("cache", "surrogate-control"),
  ("cache", "vary-explosion-rejection"),
  ("cache", "json-warming"),
  ("cache", "large-object-cache"),
  ("cache", "large-object-over-memory-not-cached"),
  ("cache", "huge-object-streaming-disk"),
  ("cache", "streaming-disk-reservation"),
  ("cache", "disk-index-churn"),
  ("cache", "lock-starvation"),
  ("cache", "shared-streaming-disk-l2"),
  ("cache", "background-refresh"),
  ("cache", "shared-background-refresh-disabled"),
  ("cache", "admission-stale-errors"),
  ("cache", "collapsed-forwarding-metrics"),
  ("database-mitigation", "managed-postgres"),
  ("database-mitigation", "existing-postgres"),
  ("shared-state", "redis-valkey-cluster-state"),
  ("shared-state", "postgres-cluster-state"),
  ("shared-state", "redis-delay-isolation"),
  ("shared-state", "redis-disconnect-reconnect"),
  ("shared-state", "postgres-delay-isolation"),
  ("dynamic-policy", "postgres-snapshot"),
  ("dynamic-policy", "automation-api"),
  ("hot-reload", "oxirule-config"),
  ("hot-reload", "downstream-tls-only"),
  ("hot-reload", "full-config-tls-listener-rebind"),
  ("hot-reload", "telemetry-tracing-disable"),
  ("hot-reload", "admin-listener-rebind"),
  ("hot-reload", "graceful-http-drain"),
  ("hot-reload", "graceful-upgrade-drain"),
  ("hot-reload", "webtransport-stale-snapshot-drain"),
  ("lifecycle", "admin-drain-readiness"),
  ("lifecycle", "process-signal-h2-h3-drain"),
  ("config-invalid", "no-http-versions"),
  ("config-invalid", "privileged-port-unprivileged"),
  ("config-invalid", "accept-workers-without-reuseport"),
  ("config-invalid", "static-ocsp-missing-response"),
  ("config-invalid", "http3-upstream-requires-https"),
  ("config-invalid", "quic-receive-window-above-dynamic-cap"),
  ("config-invalid", "ech-config-list-missing-file"),
  ("config-invalid", "unsafe-route-path"),
  ("config-invalid", "crs-allowlist-header-selector"),
  ("config-invalid", "legacy-load-balancing-algorithm"),
  ("config-invalid", "route-multiple-targets"),
  ("config-invalid", "route-action-invalid"),
  ("config-invalid", "route-unknown-references"),
  ("proxy-routing", "exact-host-beats-wildcard"),
  ("proxy-routing", "leading-dot-host-falls-back"),
  ("proxy-routing", "longer-path-prefix-wins"),
  ("proxy-routing", "replace-prefix"),
  ("proxy-routing", "rewrite-action"),
  ("proxy-routing", "redirect-action"),
  ("proxy-routing", "host-port-and-case-normalization"),
  ("proxy-routing", "wildcard-suffix-specificity"),
  ("proxy-routing", "prefix-boundary-no-partial-match"),
  ("proxy-routing", "equal-specificity-keeps-route-order"),
  ("proxy-routing", "host-header-not-tls-sni-selects-route"),
  ("proxy-routing", "replace-prefix-exact-root-and-query"),
  ("proxy-routing", "no-matching-route-fails-closed"),
  ("proxy-routing", "pool-only-route-forwards"),
  ("proxy-routing", "route-upstream-http-version-h2-override"),
  ("proxy-headers", "forwarded-and-host-defaults"),
  ("proxy-headers", "waf-request-header-mutations"),
  ("proxy-headers", "security-response-headers"),
  ("proxy-upstream-tls", "trusted-https-upstream"),
  ("proxy-upstream-tls", "untrusted-https-upstream-fails"),
  ("proxy-upstream-tls", "health-check-tls-policy"),
  ("waf-request", "reject-path"),
  ("waf-request", "body-size-chunked"),
  ("waf-request", "monitor-mode-allows"),
  ("waf-request", "rule-mode-hit-counters"),
  ("waf", "waf-http-body-compression"),
  ("waf-crs", "request-response-full"),
  ("waf-crs", "monitor-first"),
  ("waf-request", "normalized-crs-request"),
  ("waf-request", "route-to-upstream"),
  ("waf-request", "route-to-pool"),
  ("waf-request", "set-tag-chain"),
  ("waf-request", "external-rule-file"),
  ("waf-request", "route-level-rule"),
  ("waf-response", "set-remove-response-headers"),
  ("waf-response", "response-object-model"),
  ("waf-response", "replace-5xx"),
  ("waf-response", "reject-response"),
  ("waf-response", "body-size-chunked"),
  ("waf-response", "upstream-error-replaced"),
  ("waf-validation", "route-to-pool-reserved"),
  ("waf-validation", "set-load-balancing-reserved"),
  ("waf-validation", "response-access-in-request"),
  ("waf-helpers", "response-body-scan"),
  ("waf-helpers", "header-query-cookie"),
  ("waf-helpers", "pattern-set-contains"),
  ("waf-helpers", "body-format-helper"),
  ("waf-helpers", "body-streaming-scan"),
  ("waf-helpers", "udf-body-object"),
  ("waf-person-proof", "challenge-issued"),
  (
    "waf-person-proof",
    "challenge-spam-does-not-reserve-single-use-state",
  ),
  ("waf-person-proof", "provider-mock-verify"),
  ("waf-person-proof", "provider-replay-consumes-session"),
  ("protocol-startup", "http1-only"),
  ("protocol-startup", "http1-http2"),
  ("protocol-startup", "http3-enabled-startup"),
  ("sni-forwarding", "tcp-and-quic-passthrough"),
  ("sni-forwarding", "resource-limits"),
  ("protocol-startup", "listener-reuseport-workers"),
  ("protocol-proxying", "downstream-h2-upstream-h1"),
  ("protocol-proxying", "downstream-tls-http-suite"),
  ("protocol-proxying", "downstream-sni-tls-version-override"),
  (
    "protocol-proxying",
    "remote-signer-downstream-tls-http-suite",
  ),
  ("protocol-proxying", "downstream-h2-adaptive-window-default"),
  ("protocol-proxying", "downstream-h2-upstream-h2"),
  ("protocol-proxying", "downstream-h2-upstream-h2c"),
  ("protocol-proxying", "downstream-h2-upstream-h3-pooled"),
  ("protocol-proxying", "downstream-h2-upstream-h3-one-shot"),
  (
    "protocol-proxying",
    "downstream-h2-upstream-h3-pooled-reconnect",
  ),
  ("protocol-proxying", "alt-svc-https-response"),
  ("protocol-proxying", "alt-svc-port-overrides"),
  ("protocol-proxying", "alt-svc-skip-rules"),
  ("protocol-proxying", "downstream-h3-retry"),
  ("protocol-proxying", "downstream-h3-zero-rtt-policy"),
  ("protocol-proxying", "downstream-h3-upstream-h1"),
  ("protocol-proxying", "downstream-h3-bounded-receive-window"),
  ("protocol-proxying", "downstream-h3-upstream-h2"),
  ("protocol-proxying", "downstream-h3-upstream-h2c"),
  ("protocol-startup", "pq-tls-groups"),
];
