set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(OXIBELT_RISCV64_TOOLCHAIN_PREFIX "/x-tools/riscv64-unknown-linux-musl/bin/riscv64-unknown-linux-musl-")
set(OXIBELT_RISCV64_SYSROOT "/x-tools/riscv64-unknown-linux-musl/riscv64-unknown-linux-musl/sysroot")

set(CMAKE_C_COMPILER "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_COMPILER "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}g++")
set(CMAKE_AR "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}ar")
set(CMAKE_LINKER "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}ld")
set(CMAKE_NM "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}nm")
set(CMAKE_OBJCOPY "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}objcopy")
set(CMAKE_OBJDUMP "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}objdump")
set(CMAKE_RANLIB "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}ranlib")
set(CMAKE_STRIP "${OXIBELT_RISCV64_TOOLCHAIN_PREFIX}strip")

set(CMAKE_SYSROOT "${OXIBELT_RISCV64_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${OXIBELT_RISCV64_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(OXIBELT_RISCV64_OBJECT_FLAGS
    "-ffunction-sections -fdata-sections -fPIC -march=rv64gc -mabi=lp64d -mcmodel=medany")
set(CMAKE_C_FLAGS_INIT "${OXIBELT_RISCV64_OBJECT_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${OXIBELT_RISCV64_OBJECT_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${OXIBELT_RISCV64_OBJECT_FLAGS}")

