use std::collections::{BTreeMap, HashMap, HashSet};

use anyhow::bail;
use serde_json::Value;

use super::cli::{BackendResolution, SharedArgs};
use super::gateway_policy::{self, ListenerPolicy, ReferenceGrantInfo, RoutePolicyDecision};
use super::model::{Diagnostic, KubernetesObject, ObjectKey, object_ref as model_object_ref};

#[path = "translate/backend_tls.rs"]
mod backend_tls;
#[path = "translate/filters.rs"]
mod filters;
#[path = "translate/generated.rs"]
mod generated;
#[path = "translate/grpc.rs"]
mod grpc;
#[path = "translate/http.rs"]
mod http;
#[path = "translate/l4.rs"]
mod l4;
#[path = "translate/render.rs"]
mod render;

use generated::*;

#[cfg(test)]
#[path = "translate/tests.rs"]
mod tests;

const UPSTREAM_SCHEME_ANNOTATION: &str = "oxibelt.dev/upstream-scheme";
const GENERATED_HEADER: &str = "# Generated by oxibelt-gateway-controller. Do not edit.\n\
# This file is controller-owned and is intended to be included from the base OxiBelt config.\n\n";

#[derive(Debug, Clone)]
pub struct RenderedConfig {
  pub toml: String,
  pub assets: Vec<RenderedAsset>,
  pub diagnostics: Vec<Diagnostic>,
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct RenderedAsset {
  pub data_key: String,
  pub managed_path: String,
  pub content: String,
}

#[derive(Debug, Clone)]
struct ServiceInfo {
  namespace: String,
  name: String,
  ports: Vec<ServicePort>,
  scheme: String,
}

#[derive(Debug, Clone)]
struct ServicePort {
  name: Option<String>,
  port: u16,
  target_port: Option<ServiceTargetPort>,
  protocol: String,
}

#[derive(Debug, Clone)]
enum ServiceTargetPort {
  Number(u16),
  Name,
}

#[derive(Debug, Clone)]
struct GatewayInfo {
  namespace: String,
  name: String,
  listeners: Vec<ListenerInfo>,
}

#[derive(Debug, Clone)]
struct ListenerInfo {
  name: Option<String>,
  port: u16,
  protocol: String,
  hostname: Option<String>,
  tls_mode: Option<String>,
  allowed_routes: ListenerPolicy,
}

#[derive(Default)]
struct TranslationState {
  backend_resolution: BackendResolution,
  services: HashMap<ObjectKey, ServiceInfo>,
  namespace_labels: HashMap<String, BTreeMap<String, String>>,
  gateway_classes: HashSet<String>,
  gateways: HashMap<ObjectKey, GatewayInfo>,
  reference_grants: Vec<ReferenceGrantInfo>,
  pools: BTreeMap<String, GeneratedPool>,
  external_auth: BTreeMap<String, GeneratedExternalAuth>,
  routes: Vec<GeneratedRoute>,
  sni_rules: Vec<GeneratedSniRule>,
  stream_listeners: BTreeMap<String, GeneratedStreamListener>,
  stream_pools: BTreeMap<String, GeneratedStreamPool>,
  backend_tls: HashMap<ObjectKey, BackendTlsDecision>,
  assets: BTreeMap<String, RenderedAsset>,
  diagnostics: Vec<Diagnostic>,
}

#[derive(Clone)]
struct GeneratedCheckpoint {
  pools: BTreeMap<String, GeneratedPool>,
  external_auth: BTreeMap<String, GeneratedExternalAuth>,
  routes: Vec<GeneratedRoute>,
  sni_rules: Vec<GeneratedSniRule>,
  stream_listeners: BTreeMap<String, GeneratedStreamListener>,
  stream_pools: BTreeMap<String, GeneratedStreamPool>,
}

pub fn translate_objects(
  objects: &[KubernetesObject],
  args: &SharedArgs,
) -> anyhow::Result<RenderedConfig> {
  let mut state = TranslationState {
    backend_resolution: args.backend_resolution,
    namespace_labels: gateway_policy::namespace_labels(objects),
    ..Default::default()
  };
  state.index_supporting_objects(objects, args)?;
  state.index_backend_tls(objects);
  state.translate_l4_routes(objects, args);
  for object in objects {
    let checkpoint = state.generated_checkpoint();
    let diagnostic_start = state.diagnostics.len();
    match object.kind.as_str() {
      "GRPCRoute" => state.translate_grpc_route(object),
      "HTTPRoute" => state.translate_http_route(object),
      "TLSRoute" => state.translate_tls_route(object),
      "TCPRoute" | "UDPRoute" => {}
      _ => {}
    }
    if state.diagnostics[diagnostic_start..]
      .iter()
      .any(|diagnostic| diagnostic.severity == super::model::DiagnosticSeverity::Error)
    {
      state.restore_generated(checkpoint);
    }
  }
  Ok(RenderedConfig {
    toml: render::render_toml(&state, args),
    assets: state.assets.into_values().collect(),
    diagnostics: state.diagnostics,
  })
}

impl TranslationState {
  fn generated_checkpoint(&self) -> GeneratedCheckpoint {
    GeneratedCheckpoint {
      pools: self.pools.clone(),
      external_auth: self.external_auth.clone(),
      routes: self.routes.clone(),
      sni_rules: self.sni_rules.clone(),
      stream_listeners: self.stream_listeners.clone(),
      stream_pools: self.stream_pools.clone(),
    }
  }

  fn restore_generated(&mut self, checkpoint: GeneratedCheckpoint) {
    self.pools = checkpoint.pools;
    self.external_auth = checkpoint.external_auth;
    self.routes = checkpoint.routes;
    self.sni_rules = checkpoint.sni_rules;
    self.stream_listeners = checkpoint.stream_listeners;
    self.stream_pools = checkpoint.stream_pools;
  }

  fn index_supporting_objects(
    &mut self,
    objects: &[KubernetesObject],
    args: &SharedArgs,
  ) -> anyhow::Result<()> {
    for object in objects {
      match object.kind.as_str() {
        "Service" => match parse_service(object) {
          Ok(service) => {
            self.services.insert(object.key(), service);
          }
          Err(error) => self.diagnostics.push(Diagnostic::error(
            model_object_ref(object),
            format!("invalid Service: {error:#}"),
          )),
        },
        "GatewayClass"
          if string_at(&object.spec, &["controllerName"])
            == Some(args.controller_name.as_str()) =>
        {
          self.gateway_classes.insert(object.name().to_string());
        }
        "ReferenceGrant" => {
          if let Some(grant) = gateway_policy::parse_reference_grant(object) {
            self.reference_grants.push(grant);
          }
        }
        _ => {}
      }
    }
    for object in objects {
      if object.kind == "Gateway"
        && let Some(gateway) = parse_gateway(object, &self.gateway_classes)
      {
        self.gateways.insert(object.key(), gateway);
      }
    }
    Ok(())
  }

  fn translate_tls_route(&mut self, route: &KubernetesObject) {
    let attachments = self.attachments_for(route, &["TLS"]);
    if attachments.is_empty() {
      self.diagnostics.push(Diagnostic::warning(
        model_object_ref(route),
        "route is not attached to an in-scope TLS Gateway listener",
      ));
      return;
    }

    let route_hosts = string_array_at(&route.spec, &["hostnames"]);
    let rules = route.spec.get("rules").and_then(Value::as_array);
    let Some(rules) = rules else {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        "TLSRoute spec.rules is required",
      ));
      return;
    };

    for attachment in attachments {
      if attachment.listener.tls_mode.as_deref() != Some("Passthrough") {
        self.diagnostics.push(Diagnostic::error(
          model_object_ref(route),
          "TLSRoute requires a Gateway TLS listener with tls.mode = Passthrough",
        ));
        continue;
      }
      let hosts = intersect_hosts(&route_hosts, attachment.listener.hostname.as_deref());
      for (rule_index, rule) in rules.iter().enumerate() {
        let source = format!(
          "TLSRoute/{}/{} rule {} via Gateway/{}/{}",
          route.namespace(),
          route.name(),
          rule_index,
          attachment.gateway.namespace,
          attachment.gateway.name,
        );
        let Some(target) =
          self.tls_target(route, rule.get("backendRefs").and_then(Value::as_array))
        else {
          continue;
        };
        self.sni_rules.push(GeneratedSniRule {
          source,
          name: sanitize_name(&format!(
            "gwapi-tls-{}-{}-{}",
            route.namespace(),
            route.name(),
            rule_index
          )),
          server_names: if hosts.is_empty() {
            vec!["*".to_string()]
          } else {
            hosts.clone()
          },
          target,
        });
      }
    }
  }

  fn tls_target(
    &mut self,
    route: &KubernetesObject,
    backend_refs: Option<&Vec<Value>>,
  ) -> Option<String> {
    let Some(backend_refs) = backend_refs else {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        "TLSRoute rule.backendRefs is required",
      ));
      return None;
    };
    let nonzero = backend_refs
      .iter()
      .filter(|backend| u32_at(backend, &["weight"]).unwrap_or(1) > 0)
      .collect::<Vec<_>>();
    if nonzero.len() != 1 {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        "TLSRoute v1 supports exactly one nonzero Service backendRef",
      ));
      return None;
    }
    let backend = nonzero[0];
    if !backend_ref_is_service(backend) {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        "TLSRoute only supports Kubernetes Service backendRefs",
      ));
      return None;
    }
    let name = string_at(backend, &["name"])?;
    let namespace = string_at(backend, &["namespace"]).unwrap_or(route.namespace());
    if namespace != route.namespace()
      && !self.reference_allowed(route, "TLSRoute", namespace, "Service", name)
    {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        format!("cross-namespace backendRef to {namespace}/{name} requires ReferenceGrant"),
      ));
      return None;
    }
    let key = ObjectKey {
      namespace: namespace.to_string(),
      name: name.to_string(),
    };
    let Some(service) = self.services.get(&key) else {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        format!("backend Service {namespace}/{name} was not found in input snapshot"),
      ));
      return None;
    };
    let Some(port) = backend_port(backend, service) else {
      self.diagnostics.push(Diagnostic::error(
        model_object_ref(route),
        format!("backend Service {namespace}/{name} does not expose the referenced port"),
      ));
      return None;
    };
    Some(format!(
      "{}.{}.svc.cluster.local:{}",
      service.name, service.namespace, port
    ))
  }

  fn reference_allowed(
    &self,
    route: &KubernetesObject,
    from_kind: &str,
    target_namespace: &str,
    target_kind: &str,
    target_name: &str,
  ) -> bool {
    gateway_policy::reference_allowed(
      &self.reference_grants,
      route,
      from_kind,
      target_namespace,
      target_kind,
      target_name,
    )
  }

  fn attachments_for(
    &mut self,
    route: &KubernetesObject,
    protocols: &[&str],
  ) -> Vec<RouteAttachment> {
    let mut attachments = Vec::new();
    let parent_refs = route
      .spec
      .get("parentRefs")
      .and_then(Value::as_array)
      .cloned()
      .unwrap_or_default();
    for parent in parent_refs {
      if let Some(field) = unsupported_field(
        &parent,
        &["group", "kind", "name", "namespace", "sectionName", "port"],
      ) {
        self.diagnostics.push(Diagnostic::error(
          model_object_ref(route),
          format!("parentRef.{field} is unsupported"),
        ));
        continue;
      }
      if !parent_ref_is_gateway(&parent) {
        continue;
      }
      let Some(parent_name) = string_at(&parent, &["name"]) else {
        continue;
      };
      let parent_namespace = string_at(&parent, &["namespace"]).unwrap_or(route.namespace());
      let key = ObjectKey {
        namespace: parent_namespace.to_string(),
        name: parent_name.to_string(),
      };
      let Some(gateway) = self.gateways.get(&key) else {
        continue;
      };
      let section_name = string_at(&parent, &["sectionName"]);
      let parent_port = u16_at(&parent, &["port"]);
      for listener in &gateway.listeners {
        if !protocols
          .iter()
          .any(|protocol| *protocol == listener.protocol)
        {
          continue;
        }
        if section_name.is_some() && listener.name.as_deref() != section_name {
          continue;
        }
        if parent_port.is_some() && parent_port != Some(listener.port) {
          continue;
        }
        match gateway_policy::listener_allows_route(
          &listener.allowed_routes,
          route,
          &gateway.namespace,
          &listener.protocol,
          listener.tls_mode.as_deref(),
          &self.namespace_labels,
        ) {
          RoutePolicyDecision::Allowed => {}
          RoutePolicyDecision::Denied => continue,
          RoutePolicyDecision::Invalid(error) => {
            self.diagnostics.push(Diagnostic::warning(
              model_object_ref(route),
              format!(
                "route is not permitted by Gateway/{}/{} listener allowedRoutes: {error}",
                gateway.namespace, gateway.name,
              ),
            ));
            continue;
          }
        }
        attachments.push(RouteAttachment {
          gateway: gateway.clone(),
          listener: listener.clone(),
        });
      }
    }
    attachments
  }
}

#[derive(Debug, Clone)]
struct RouteAttachment {
  gateway: GatewayInfo,
  listener: ListenerInfo,
}

fn parse_service(object: &KubernetesObject) -> anyhow::Result<ServiceInfo> {
  let mut ports = Vec::new();
  for port in object
    .spec
    .get("ports")
    .and_then(Value::as_array)
    .cloned()
    .unwrap_or_default()
  {
    let Some(number) = u16_at(&port, &["port"]) else {
      continue;
    };
    ports.push(ServicePort {
      name: string_at(&port, &["name"]).map(str::to_string),
      port: number,
      target_port: service_target_port(&port),
      protocol: string_at(&port, &["protocol"])
        .unwrap_or("TCP")
        .to_ascii_uppercase(),
    });
  }
  let scheme = object
    .metadata
    .annotations
    .get(UPSTREAM_SCHEME_ANNOTATION)
    .map(String::as_str)
    .unwrap_or("http");
  if !matches!(scheme, "http" | "https") {
    bail!(
      "Service/{}/{} annotation {UPSTREAM_SCHEME_ANNOTATION} must be http or https",
      object.namespace(),
      object.name()
    );
  }
  Ok(ServiceInfo {
    namespace: object.namespace().to_string(),
    name: object.name().to_string(),
    ports,
    scheme: scheme.to_string(),
  })
}

fn parse_gateway(
  object: &KubernetesObject,
  accepted_classes: &HashSet<String>,
) -> Option<GatewayInfo> {
  let class = string_at(&object.spec, &["gatewayClassName"])?;
  if !accepted_classes.contains(class) {
    return None;
  }
  let listeners = object
    .spec
    .get("listeners")
    .and_then(Value::as_array)
    .cloned()
    .unwrap_or_default()
    .into_iter()
    .filter_map(|listener| {
      let protocol = string_at(&listener, &["protocol"])?.to_string();
      let port = u16_at(&listener, &["port"])?;
      Some(ListenerInfo {
        name: string_at(&listener, &["name"]).map(str::to_string),
        port,
        protocol,
        hostname: string_at(&listener, &["hostname"]).map(str::to_string),
        tls_mode: string_at(&listener, &["tls", "mode"]).map(str::to_string),
        allowed_routes: gateway_policy::parse_listener_policy(&listener),
      })
    })
    .collect();
  Some(GatewayInfo {
    namespace: object.namespace().to_string(),
    name: object.name().to_string(),
    listeners,
  })
}

fn backend_ref_is_service(backend: &Value) -> bool {
  let group = string_at(backend, &["group"]).unwrap_or("");
  let kind = string_at(backend, &["kind"]).unwrap_or("Service");
  group.is_empty() && kind == "Service"
}

fn parent_ref_is_gateway(parent: &Value) -> bool {
  let group = string_at(parent, &["group"]).unwrap_or(gateway_policy::GATEWAY_GROUP);
  let kind = string_at(parent, &["kind"]).unwrap_or("Gateway");
  group == gateway_policy::GATEWAY_GROUP && kind == "Gateway"
}

fn backend_port(backend: &Value, service: &ServiceInfo) -> Option<u16> {
  backend_service_port(backend, service).map(|port| port.port)
}

fn backend_service_port<'a>(backend: &Value, service: &'a ServiceInfo) -> Option<&'a ServicePort> {
  if let Some(port) = u16_at(backend, &["port"]) {
    return service
      .ports
      .iter()
      .find(|candidate| candidate.port == port);
  }
  if let Some(name) = string_at(backend, &["port"]) {
    return service
      .ports
      .iter()
      .find(|candidate| candidate.name.as_deref() == Some(name));
  }
  None
}

fn endpoint_slice_discovery_port(
  service_port: &ServicePort,
) -> Result<GeneratedKubernetesDiscoveryPort, &'static str> {
  if let Some(name) = &service_port.name {
    return Ok(GeneratedKubernetesDiscoveryPort::Name(name.clone()));
  }
  match &service_port.target_port {
    Some(ServiceTargetPort::Number(port)) => Ok(GeneratedKubernetesDiscoveryPort::Number(*port)),
    Some(ServiceTargetPort::Name) => Err(
      "EndpointSlice backend resolution requires unnamed Service ports to use numeric targetPort",
    ),
    None => Ok(GeneratedKubernetesDiscoveryPort::Number(service_port.port)),
  }
}

fn service_target_port(port: &Value) -> Option<ServiceTargetPort> {
  let target = port.get("targetPort")?;
  if let Some(number) = target.as_u64().and_then(|raw| u16::try_from(raw).ok()) {
    return Some(ServiceTargetPort::Number(number));
  }
  target.as_str().map(|_| ServiceTargetPort::Name)
}

fn intersect_hosts(route_hosts: &[String], listener_hostname: Option<&str>) -> Vec<String> {
  let Some(listener) = listener_hostname else {
    return route_hosts.to_vec();
  };
  if route_hosts.is_empty() {
    return vec![listener.to_string()];
  }
  route_hosts
    .iter()
    .filter(|host| host_intersects(host, listener))
    .cloned()
    .collect()
}

fn host_intersects(route_host: &str, listener_host: &str) -> bool {
  host_matches(route_host, listener_host) || host_matches(listener_host, route_host)
}

fn host_matches(pattern: &str, host: &str) -> bool {
  let pattern = pattern.trim_end_matches('.').to_ascii_lowercase();
  let host = host.trim_end_matches('.').to_ascii_lowercase();
  if pattern == "*" {
    return true;
  }
  if let Some(suffix) = pattern.strip_prefix("*.") {
    return host.ends_with(&format!(".{suffix}")) && host != suffix;
  }
  pattern == host
}

fn sanitize_name(value: &str) -> String {
  let mut out = String::new();
  for ch in value.chars() {
    if ch.is_ascii_alphanumeric() {
      out.push(ch.to_ascii_lowercase());
    } else if matches!(ch, '-' | '_' | '.') {
      out.push(ch);
    } else {
      out.push('-');
    }
  }
  while out.contains("--") {
    out = out.replace("--", "-");
  }
  out.trim_matches('-').to_string()
}

fn string_at<'a>(value: &'a Value, path: &[&str]) -> Option<&'a str> {
  let mut current = value;
  for key in path {
    current = current.get(*key)?;
  }
  current.as_str()
}

fn string_array_at(value: &Value, path: &[&str]) -> Vec<String> {
  let mut current = value;
  for key in path {
    let Some(next) = current.get(*key) else {
      return Vec::new();
    };
    current = next;
  }
  current
    .as_array()
    .map(|items| {
      items
        .iter()
        .filter_map(Value::as_str)
        .map(str::to_string)
        .collect()
    })
    .unwrap_or_default()
}

fn u16_at(value: &Value, path: &[&str]) -> Option<u16> {
  let raw = u64_at(value, path)?;
  u16::try_from(raw).ok()
}

fn u32_at(value: &Value, path: &[&str]) -> Option<u32> {
  let raw = u64_at(value, path)?;
  u32::try_from(raw).ok()
}

fn u64_at(value: &Value, path: &[&str]) -> Option<u64> {
  let mut current = value;
  for key in path {
    current = current.get(*key)?;
  }
  current.as_u64()
}

fn unsupported_field<'a>(value: &'a Value, allowed: &[&str]) -> Option<&'a str> {
  value
    .as_object()?
    .keys()
    .find(|key| !allowed.contains(&key.as_str()))
    .map(String::as_str)
}
