global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: oxibelt
    metrics_path: /metrics
    static_configs:
      - targets:
          - oxibelt:9090
        labels:
          service: oxibelt
